### ISSUE TITLE
epsg lookup is undocumented - should we include this or use something from proj4?

### ISSUE THREAD

**Issue by lwasser** [earthlab/earthpy#154]
currently we have an epsg dictionary that allows you to lookup the prj string for an epsg code rather than having to google it! this gives you units and such. 

We need to add epsg to the documentation of earthpy. 

et.epsg["epsg-code-here"] 

This issue is probably do we want to keep or **remove this** from our package??!!  @joemcglinchy can you please look into this?? ... it could be a function that uses `proj4` to get the string??

**Comment by joemcglinchy** [comment]
at this point I would say let us leave it in earthpy! I have done some digging and have struggled at how to produce the same string we have in the `epsg.json` dictionary. For example, the first entry:

"29188": "+proj=utm +zone=18 +south +ellps=aust_SA +towgs84=-66.87,4.37,-38.52,0,0,0,0 +units=m +no_defs"

I can run 
```
from pyproj import Proj
p = Proj(init='epsg:29188')
print(p.srs)
--> '+units=m +init=epsg:29188 '
```
The closest I can get is by calling `.to_latlong().srs`, which isn't even correct.
```
print(p.to_latlong().srs)
--> b' +proj=latlong +ellps=aust_SA +towgs84=-66.87,4.37,-38.52,0,0,0,0'
```

I know that our `epsg.json` dictionary is coming from a file in the PyProj package, but I'm not seeing how  those strings are directly callable from a Proj object. My vote is to keep the dictionary and periodically check for updates from PyProj, unless someone has a better understanding of how to produce that string using the PyProj library.

**Comment by lwasser** [comment]
if we keep this we will need to add documentation!! Call it in the lessons !! @nkorinek

**Comment by mbjoseph** [comment]
We can document this by wrapping the existing `epsg` object in a function with a docstring. The wrapper will return what is currently used to define `epsg`. 

See `earthpy/__init__.py` for where this should happen.

**Comment by lwasser** [comment]
closing this via the above merged PR!
