### ISSUE TITLE
Autogenerate API documentation

### ISSUE THREAD

**Issue by mbjoseph** [earthlab/earthpy#157]
Currently a large chunk of earthpy documentation is duplicated from docstrings in the source code. It would be better to automatically generate API documentation from the docstrings using Sphinx, and we can do so while keeping numpy style docstrings using the napoleon extension (https://www.sphinx-doc.org/en/master/usage/extensions/napoleon.html). 

The napoleon extension is also used by rasterio to create their API docs: https://rasterio.readthedocs.io/en/latest/api/index.html

**Comment by lwasser** [comment]
this will be good. i'll have my interns start by working on updating the documentation to be a bit more robust.
