### ISSUE TITLE
Error with strack_raster_tifs

### ISSUE THREAD

**Issue by zstatmanweil** [earthlab/earthpy#159]
Hello,

This is my first time adding an issue on Github so not sure how to proceed exactly, but I am getting an error when I try to run the stack_raster_tifs function that reads "module 'rasterio' has no attribute 'io'" for line 160

Should the code be rasterio._io.DatasetReader: ?

Thank you!

**Comment by lwasser** [comment]
hey @zstatmanweil !! Thank you for your issue! And congrats on submitting your first issue to GitHub! that's awesome! I think looking at the code now, I should rewrite this test here:

https://github.com/earthlab/earthpy/blob/master/earthpy/spatial.py#L160

in a way that doesn't call the object type. I can fix this but my other question for you is - are you definitely providing the function with a list of paths to a raster? And also what version of rasterio do you have?

**Comment by zstatmanweil** [comment]
Hi @lwasser ! Thanks for the response and support :-)

In answer to your second question: I am using rasterio version 0.36.0

In answer to your first: I believe I am providing my function a list of paths to several landsat band tifs (but I am also relatively new to coding so would not be surprised if I am doing something wrong). I successfully stacked the same landsat bands using this method [here](https://gis.stackexchange.com/questions/223910/using-rasterio-or-gdal-to-stack-multiple-bands-without-using-subprocess-commands) and wanted to try the earthpy function as well because I am using some of your tutorials. I believe both require an input of a list of paths so I don't think that is my problem...

Thanks again!

**Comment by lwasser** [comment]
Ahhhh ok so are you by chance using an old version of rasterio. the older version called the object a `RasterReader` or something like that. Sometime around version 1.x it was updated to `DatasetReader`. this is why that line is failing on your computer. Are you running on windows 32 bit by chance? or anaconda 32 bit. If you are you can only install the older version of rasterio via conda. This will likely cause a few issues (i suspect anyway). 

Version 1.0.13 is the most current
https://pypi.org/project/rasterio/

We will definitely fix the code so it wont fail however as i know a much better way to write that test! but you may run into other issues with that version of rasterio. So good to hear you're using our tutorials and earthpy! I appreciate this issue.

**Comment by zstatmanweil** [comment]
I am running on windows 64 bit and anaconda 64 bit but I typically install my packages through Anaconda Navigator rather than conda and 0.36.0 was the newest available. I now have successfully installed the most recent version though and the function works! Thank you so much - I bet I would have run into a problems with that old version and had no idea what was going on. 

Thanks again and I am enjoying the tutorials very much!

**Comment by lwasser** [comment]
Oh fantastic! That's interesting that you had such a dated version. I jumped to 32 bit conda because .36 is actually the version that the 32 bit windows envt supports. Anyway SO GLAD this worked for you. If you are comfortable with it, i'll go ahead and close this issue (when i hear back that you are ok with my closing it). I'll then open a new issue for us to update that test for the dataset reader object  test (the code that was causing you issues) independently. It is great for us to get this feedback as it helps us improve earthpy! thank you!

**Comment by zstatmanweil** [comment]
Yes, please close. Thank you!

**Comment by lwasser** [comment]
Great. thank you @zstatmanweil  closing this issue!! :)
