### ISSUE TITLE
Earthpy Needs a license

### ISSUE THREAD

**Issue by lwasser** [earthlab/earthpy#163]
Hey guys! i want to secure the earthpy name on pypi. This means we  need a license file. Any thoughts on this? MIT seems fairly standard. I'm very open to thoughts on this however! Perhaps we could once again look to

- [rasterio](https://github.com/mapbox/rasterio/blob/master/LICENSE.txt)
- [Geopandas here](https://github.com/geopandas/geopandas/blob/master/LICENSE.txt)

**Comment by mbjoseph** [comment]
MIT sounds good to me!

**Comment by lwasser** [comment]
for the time being and after chatting with @mbjoseph i applied the BSD 3 clause license similar to geopandas. [see here.](https://github.com/earthlab/earthpy/blob/master/LICENSE). Closing this for now but we can reopen if needbe!
