### ISSUE TITLE
When we finish implementing the norm diff func and potentially stack() create a new release

### ISSUE THREAD

**Issue by lwasser** [earthlab/earthpy#165]
let's not forget to create a new release with a zenodo key & then i'll update pypi. so steps involved

1. create release
2. update zenodo badge accordingly
3. create new pypi tarball
4. push to pypi

While we are at it a black badge might be nice to have in the readme. I'd also like to generate a list of contributors

**Comment by jlpalomino** [comment]
I will create a new release for earthpy and then update the Zenodo badge in the README.md using the universal DOI (agnostic to specific release/version).  I will also create the list of contributors.

**Comment by lwasser** [comment]
@jlpalomino  has this been done? can we close this issue? if so please close it!

**Comment by jlpalomino** [comment]
@lwasser The new release has been created, but I believe we are going to fix the version issue by completing a new release that includes contributors. We need to determine who is listed as a contributor and the appropriate contributor type.

**Comment by lwasser** [comment]
ok! i have a version 0.6.2 release on zenodo and pypi now!! closing this issue!! I think our current list for zenodo is reasonable although i could see tim being a contributor as he only really contributed a few small things rather than contributing to the higher level creation of the package, docs and testing. but i'm ok with it as is for now!!
