### ISSUE TITLE
updating stack function naming and return

### ISSUE THREAD

**Issue by joemcglinchy** [earthlab/earthpy#167]
in looking at the `stack_raster_tifs` and `stack` workflow, I had a couple of ideas to perhaps enhance the readability and usability of these 2 functions. Here is what I propose:

1) Since this function is being used in an environment most likely for exploratory analytics and data investigation, the stack workflow should return a nD array for the user to further analyze in their python environment. This should be the default, with the option to write out a TIF file if they desire. 

2) With the behavior above, I feel the function `stack` should be the one called from `earthpy.spatial`, defined as `stack(band_paths, out_path='', write_raster=False)`. If `write_raster == True` then call the current functionality of the stack function, which would be renamed to `stack_bands` or something similar and more general, as this function takes into account the profile of the input data so if the first item in the list is a JPG or JP2 file, for instance, it will be saved with that driver. We should also check for that in the file name given by `out_path`.

**Comment by joemcglinchy** [comment]
I think cropping using the geometry (however it is provided) along with a set of bands would be a good function to have, but before incorporating it into a general `stack` function like we have right now it would be good to provide it as a separate function, e.g. `stack_and_crop` so as to not complicate the current function. If we can get that separate function working with the crop functionality, then we can just call out to it if the user provides the appropriate parameters.

Cropping a numpy array would be a different case altogether. I think that would involve:

1) defining the 'cropping geometry'... is it a geojson or geopandas object? 
2) calculating the extent of the array given a matching affine transform. Can we be sure the affine transform is associated with the array provided? Is the geometry specified within that extent? Does the geometry go beyond the image array?
3) in the ideal case, the geometry will be fully contained within the image extent. If that is the case, then the easiest (best?) thing to do is calculate the corner pixels based on the image's affine transform (which will need to be provided as a parameter since numpy has none of that) and the extent of the geometry provided.

This case seems like it can get a little complicated. It's almost like you need a geospatial array class to carry through everything, with attributes such as the numpy array, profile/affine transform, epsg, etc.

**Comment by lwasser** [comment]
agreed!! also i have no desire to deal with image rotation. i think rasterio handles it tho which is why some of me just wants to use the rasterio `mask()` function  as a base. but we have to do it then when the array is  a reader object.  stack could call however the `crop_image()` function. @mbjoseph  is working on this now i think.

**Comment by mbjoseph** [comment]
FWIW I like @joemcglinchy's suggestion to return an array and not write to the filesystem by default - it seems more polite to only do so if the user changes the `write_raster` argument. 

I also think we should keep stacking and cropping functions separate, as they are both useful on their own. We should probably move cropping discussions to another issue to keep this one on topic.

**Comment by lwasser** [comment]
hey @mbjoseph i'm happy to move it but i think it impacts the stack function potentially too. Here is why. when you open data using rasterio you get a raster reader object. as soon as you mask() or read() the data it is now a non spatial numpy array. 

At this point you can no longer call the mask() function UNLESS -- this is a big unless there is a clever way to create a datasetreader object using a numpy array and a .profile metadata object. (this could be worth looking into).

If the paragraph above is not possible, then you have to mask when you open the data ie you have to mask when you are stacking while the data are still reader objects. This just impacts how we think about the stack function. does that make sense? they are both useful on their own but they actually can't happen together unless they are nested. Or if you can do the conversion to dataset reader.

**Comment by joemcglinchy** [comment]
closed with PR #170
