### ISSUE TITLE
Hillshade function - explore various ways to implement the hillshade calculation

### ISSUE THREAD

**Issue by lwasser** [earthlab/earthpy#177]
@jlpalomino  this is for you to work on various approaches to histogram implementation in earthpy.

**Comment by lwasser** [comment]
@jlpalomino  will you please link this issue to your PR and be sure it gets CLOSED once you work through the PR review process and that PR is merged?

**Comment by jlpalomino** [comment]
@lwasser I will do this when that PR is opened. The current PR for hillshade is only focused on adding tests and modifying the to existing hillshade calculation.

**Comment by lwasser** [comment]
@jlpalomino we have so many other things to do and the hillshade calculation i think works pretty well. i'm going to close this issue for now and we can address it in the future IF we have some free time to work on this. :) i don't think it's necessary given things work now!
