### ISSUE TITLE
Hide helper functions in docs -- intern task??

### ISSUE THREAD

**Issue by lwasser** [earthlab/earthpy#186]
1. set up option sin autodoc to hide helper functions
2. rename helpers using dunder `__`

* looks like we can flag helper functions to private so that it doesn't show the helper functions
* solution - rename using `clip_points` --> `__clip_points`
* mask helper functions
* others??

Add plots to vignettes (if plot code is there it should automagically render).

**Comment by nkorinek** [comment]
The helper functions have been notated with a sunder instead of a dunder, but autodoc automatically hides the helper functions from the documentation! This issue can probably be resolved...
