### ISSUE TITLE
We need dev setup instructions for earthpy

### ISSUE THREAD

**Issue by lwasser** [earthlab/earthpy#189]

**Comment by mbjoseph** [comment]
Can we add some more info/details to this issue? I'm looking at the CONTRIBUTING file and it looks like we have instructions to set up the development environment. I can't remember specifically which dev setup instructions we thought needed to be added.

**Comment by lwasser** [comment]
ahhhh @mbjoseph you know i thought we had those but because it's been a week or two since i've worked on earthpy, i had forgotten where it lived

https://github.com/earthlab/earthpy/blob/master/CONTRIBUTING.rst

@nkorinek @mirob9363  please note that the instructions for setting up the envt are located in the link above - the contributing doc. @mbjoseph i think that this issue is actually resolved and was user (my) error :) but i'll leave it open just for a bit so that Nathan and Michelle see it!!

**Comment by lwasser** [comment]
ALl instructions are in the contributing.rst file!! closing
