### ISSUE TITLE
Finding a home for earthpy's dependencies

### ISSUE THREAD

**Issue by mbjoseph** [earthlab/earthpy#19]
Currently this repo contains an environment.yml file that is very similar (but not identical) to the [`environment.yml` file](https://github.com/earthlab/earth-analytics-python-env/blob/master/environment.yml) for the earth analytics class conda environment.

But, this package has dependencies that aren't needed for the class, and the class has dependencies that aren't needed for this package. One solution to this is to deal with the environment for this package separately from the environment for the class (but still make sure that students using the class environment can use this package). 

From what I can gather from https://python-packaging.readthedocs.io/en/latest/dependencies.html, the convention is to use `install_requires` in `setup.py` (https://github.com/earthlab/earthpy/blob/master/setup.py#L33-L34) to specify the minimal set of requirements for users to install and use the package. But, it also seems like we could use a `requirements.txt` file or an `environment.yml` file. 

**So my question is:** Which of the three options (`install_requires`, `requirements.txt`, and `environment.yml`) is better in this case for ensuring that this package complies with typical practice, and that the package works with the earth analytics class conda environment?

**Comment by betatim** [comment]
As a user of this package I would expect `pip install earthpy` to take care of installing all the dependencies (except for non Python packages). This means the dependencies should be listed in `install_requires`.

For dependencies that can't be installed by `pip` (non Python packages) there are usually instructions in the `README` and a check in `setup.py` to try and determine if those dependencies were installed or not and output a message telling users that they need to fix up something else first.

**Comment by lwasser** [comment]
@betatim can we use conda-forge rather than pip for dependencies? can that be specified? i am asking because of the known errors with pip and spatial libraries.

**Comment by mbjoseph** [comment]
We are going to use conda :snake:
