### ISSUE TITLE
Rename all helper functions to be _helper_name -- SUNDER!!! 

### ISSUE THREAD

**Issue by lwasser** [earthlab/earthpy#194]
we should go through all functions and add an `_` to those and update associated functions to ensure that they are "hidden" ...

We could also consider looking into whether it appears in the docs in the future to hide these items 

DUNDER: `__fun_name__`
SUNDER: `_fun_name`

**Comment by lwasser** [comment]
hey @mirob9363 @nkorinek are there any helpers left without the SUNDER added? And can one of you please add the PR's to this issue that address that! Nathan's clip PR would be included as would Michelle's WIP for the MASK function. And potentially i think plot_legend has atleast one?

**Comment by lwasser** [comment]
[This PR](https://github.com/earthlab/earthpy/pull/237) addresses helpers for the mask function

**Comment by nkorinek** [comment]
https://github.com/earthlab/earthpy/pull/205 addresses helpers for the clip function

**Comment by mirob9363** [comment]
The changes we made to mask.py merged in https://github.com/earthlab/earthpy/pull/237 accounts for all the helper function renaming there!

**Comment by lwasser** [comment]
woo hoo!! i think we've covered it all at this point SO... i will close this issue. if we have something that is missing we can always reopen. Thank you BOTH for working on this :)
