### ISSUE TITLE
Get started docs are out of date

### ISSUE THREAD

**Issue by mbjoseph** [earthlab/earthpy#203]
## Identify the Documentation Element That You Propose to Update

The content in `docs/get-started.rst` is out of date, and no longer reflect the modules and functions that are contained in earthpy.

## Please Identify Your Proposed Changes Below

The get started docs can be updated to reflect the new module structure and changes to the functionality included in each module. I would recommend that we keep our descriptions of the modules at a high level, rather than trying to document each function in each module (that happens automatically via autodoc and Sphinx). 

We should also think about what makes sense to put in a quick start guide - e.g., common use cases that we can illustrate with examples.

**Comment by mbjoseph** [comment]
## Things to add: 

1. Links to the vignettes 
2. Links to the API docs (but call this something that a new user could identify as important)
3. Update module descriptions to reflect new structure
4. Improve the installation instructions (e.g., use `environment.yml` to set up dependencies)

**Comment by lwasser** [comment]
this is also done!!
