### ISSUE TITLE
Updating and renaming mask functions 

### ISSUE THREAD

**Issue by mirob9363** [earthlab/earthpy#204]
I am working on some changes for the mask functions. Below are my proposed changes.  

- [x] make the first two functions `(make_cloud_mask` & `apply_cloud_mask`) private helper functions (SUNDER)
- [x] switch `vals` to an optional variable (in case the user has already created a mask they want to use 
- [x] modify code to account for if the user provides a pixel qa layer with values vs. their own mask raster 
- [x] add test for when user calls main function without `vals`
- [x] rename the functions to be clearer and more descriptive 

**I am asking for feedback on the renaming of these functions.** 

I think using the term “cloud mask” in the functions is misleading, because the functions can be used for more than just masking for clouds (i.e. snow or water). 
Some ideas for the renaming the functions are:
`make_cloud_mask` --> `_create_mask`
`apply_cloud_mask` --> `_apply_mask`
`make_apply_mask` --> `mask_array`

An aspect of the functions we also might want to modify is using the term “mask” all together to avoid confusion with rasterio’s mask. For this part, I am not quite sure what alternative term we could use, but it is something to think about! 

**Please comment your thoughts on my suggestions/other ideas you have!**

**Comment by lwasser** [comment]
@joemcglinchy @mbjoseph @jlpalomino  we'd like your input on the above mask function name change that michelle is proposing. if you recall this is to apply a cloud mast to a numpy array. it creates the mask array from the pixel_qa layer if provided with values. And then applies it to the array to be masked.
```
make_cloud_mask --> _create_mask
apply_cloud_mask --> _apply_mask
make_apply_mask --> mask_array
```
Please give us some feedback on the suggested name changes above!! 
@mirob9363  please note how i tagged our team on this comment. this notifies them directly so they can see and respond. :) we are so appreciative of your help working on this package!!

**Comment by joemcglinchy** [comment]
The "mask" term may be a candidate for confusion, I can see that. We have rasterio's `mask` and numpy's `MaskedArray`. I think we want to avoid calling it strictly `mask` because we typically use that for rasterio's mask, e.g., `from rasterio.mask import mask`. `mask_array` looks very close to `masked_array` from `numpy.ma`, so there could be unwanted confusion there. We could flip it and all it `array_mask`.  Without a better name, I'm okay with keeping it as `mask_array` for now.

**Comment by lwasser** [comment]
gosh good point @joemcglinchy just a thought... something like `mask_pixels` which at a minimum would be different from numpy.ma stuff . i know @mirob9363 can appreciate how confusing "mask" was as implemented in rasterio. most students struggled with this.

**Comment by joemcglinchy** [comment]
we can change to `secrete_array`.


feel free to delete after laughing.

**Comment by lwasser** [comment]
omg @joemcglinchy is that what the thesaurus suggested?

**Comment by joemcglinchy** [comment]
...it's an option

**Comment by mirob9363** [comment]
What I have right now is @lwasser suggestion `mask_pixels`!

**Comment by lwasser** [comment]
i kind of like that name. @joemcglinchy @mbjoseph what do you think about that?? `mask_pixels`

**Comment by mbjoseph** [comment]
Works for me - good idea to generalize the name of this function and avoid conflicts with rasterio.mask.

**Comment by joemcglinchy** [comment]
`mask_pixels` works for me as well.

**Comment by lwasser** [comment]
woo hoo. @mirob9363 i think we have a name!! `mask_pixels` :)

**Comment by mirob9363** [comment]
changes to mask.py can be found in the pull request https://github.com/earthlab/earthpy/pull/220

**Comment by lwasser** [comment]
closing this @mirob9363 by way of this pr that includes all of your edits and some new items!

https://github.com/earthlab/earthpy/pull/237
