### ISSUE TITLE
plot.py function colorbar has unused parameter

### ISSUE THREAD

**Issue by mirob9363** [earthlab/earthpy#215]
While going through the `plot.py` documentation, it has come to my attention that the function `def colorbar` has an unused parameter `aspect`. 

Was there a plan to add this parameter into the function? If not, I would like to remove this variable from the function definition.

**Comment by joemcglinchy** [comment]
I don't see where it is used. I would say go ahead and remove it.

**Comment by lwasser** [comment]
@mirob9363 go ahead and drop the aspect paramemter!!

**Comment by mirob9363** [comment]
this issue has been addressed by pull request https://github.com/earthlab/earthpy/pull/229

**Comment by lwasser** [comment]
closing this issue!! great catch @mirob9363 !!!!
