### ISSUE TITLE
Purge module-specific test fixtures from tests/conftest.py

### ISSUE THREAD

**Issue by mbjoseph** [earthlab/earthpy#218]
Any fixtures defined in tests/conftest.py are available for all tests. This is great when needed, but currently there are some fixtures in conftest.py that are only used and needed by one test module. These fixtures should be defined in that test module, instead of conftest.py. This has two benefits: 

1. Less clutter in conftest.py
2. Easier to reason about test fixtures that are defined and used in the same module

**Comment by lwasser** [comment]
let's hold off on this until we implement -- https://github.com/earthlab/earthpy/issues/219

**Comment by lwasser** [comment]
this has been implemented as well!! closing!!
