### ISSUE TITLE
Refactoring the tests - one test file per function (or function + helpers) 

### ISSUE THREAD

**Issue by mbjoseph** [earthlab/earthpy#219]
We started out defining one test module per earthpy module, and then transitioned to defining one test module per function or group of functions in earthpy modules. We should choose one approach. 

To be consistent, we could refactor the tests so that one function or groups of related functions are tested in one test module, rather than using  a one to one mapping of earthpy modules to test modules. @lwasser is that your preference?

**Comment by lwasser** [comment]
We will reorganize the tests so there is one file named `test_func_name.py` per function!!

**Comment by lwasser** [comment]
this is done!!
