### ISSUE TITLE
Functions That Need Reproducible Examples in Docstrings

### ISSUE THREAD

**Issue by lwasser** [earthlab/earthpy#242]
We need to ensure all docstrings have reproducible examples of how to call the function.

**Comment by mirob9363** [comment]
I can do this!

**Comment by lwasser** [comment]
@mirob9363 i think you worked on this issue. can you please
1. check off what you have addressed in the list above and 
2. link to a PR that you made that addressed this issue (if one exists?)

**Comment by mirob9363** [comment]
`earthpy.plot.draw_legend` was addressed in the PR https://github.com/earthlab/earthpy/pull/246 
`earthpy.plot.make_col_list` is addressed in the open PR https://github.com/earthlab/earthpy/pull/252

**Comment by lwasser** [comment]
ok closing this!! thank you @mirob9363 !!!
