### ISSUE TITLE
pip install earthpy on windows 10 with Anaconda 3 does not install example-data folder

### ISSUE THREAD

**Issue by joemcglinchy** [earthlab/earthpy#245]
*FEEL FREE TO DELETE IF THIS IS IDENTIFIED ALREADY OR FIXED BY AN UPCOMING RELEASE*

**Describe the bug**
pip install earthpy on windows with Anaconda 3 does not install example-data folder. This causes failure to import clip module, or earthpy as a whole.

**To Reproduce**
1. activate desired environment
2. pip install earthpy
3. run code `from earthpy import clip as cl`

**Expected behavior**
I expected the `clip` module to import without error. I also expect the `example-data` folder containing `epsg.json` to be installed.

**Screenshots**
screenshot of earthpy directory after pip install
![image](https://user-images.githubusercontent.com/4762214/53111600-94893880-34fa-11e9-9985-74a82888c196.png)

traceback upon calling `from earthpy import clip as cl`
```
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-1-7aec88501a42> in <module>
      3 import numpy as np
      4 from matplotlib import pyplot as plt
----> 5 from earthpy import clip as cl

C:\anaconda3\envs\eapy_gbdx\lib\site-packages\earthpy\__init__.py in <module>
     15 
     16 epsg = json.loads(
---> 17     resource_string("earthpy", "example-data/epsg.json").decode("utf-8")
     18 )

C:\anaconda3\envs\eapy_gbdx\lib\site-packages\pkg_resources\__init__.py in resource_string(self, package_or_requirement, resource_name)
   1150         """Return specified resource as a string"""
   1151         return get_provider(package_or_requirement).get_resource_string(
-> 1152             self, resource_name
   1153         )
   1154 

C:\anaconda3\envs\eapy_gbdx\lib\site-packages\pkg_resources\__init__.py in get_resource_string(self, manager, resource_name)
   1394 
   1395     def get_resource_string(self, manager, resource_name):
-> 1396         return self._get(self._fn(self.module_path, resource_name))
   1397 
   1398     def has_resource(self, resource_name):

C:\anaconda3\envs\eapy_gbdx\lib\site-packages\pkg_resources\__init__.py in _get(self, path)
   1517 
   1518     def _get(self, path):
-> 1519         with open(path, 'rb') as stream:
   1520             return stream.read()
   1521 

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\anaconda3\\envs\\eapy_gbdx\\lib\\site-packages\\earthpy\\example-data\\epsg.json'
```

**What Operating System Are you Running?**
Windows 10 Professional

**Comment by mbjoseph** [comment]
Hi @joemcglinchy - thanks for opening this. I can't reproduce it on Windows 10, but I wonder whether it relates to this: https://stackoverflow.com/questions/7522250/how-to-include-package-data-with-setuptools-distribute

Can you try deleting the line `include_package_data=True` from setup.py (https://github.com/earthlab/earthpy/blob/master/setup.py#L21), and trying to install then import earthpy again? I suspect that might fix the problem.

**Comment by lwasser** [comment]
@joemcglinchy can you try to do

1. `pip uninstall earthpy` and then
2. `pip install earthpy` 

and let us know if it works? @mbjoseph just submitted a fix and i pushed to pypi!! i ran into the same error on my mac as did gina li on circle ci!

**Comment by joemcglinchy** [comment]
I couldn't test this on the machine that was seeing the issue (desktop was shut off for the move while I was out of town). However, I just tested this on my laptop in an environment which did not previously have Earthpy installed. Import is successful and data folder exists. Thanks #251 Closing!

**Comment by lwasser** [comment]
yay!!
