### ISSUE TITLE
Make earthpy installable from conda-forge

### ISSUE THREAD

**Issue by mbjoseph** [earthlab/earthpy#249]
EarthPy would be easier for users to install if it was on conda-forge, e.g., if they could do: `conda install -c conda-forge earthpy`. Instructions are here for adding a package to conda-forge: https://conda-forge.org/#add_recipe

One challenge we face currently is the dependency on the [download](https://github.com/choldgraf/download) package - which is not on conda-forge. To get EarthPy on conda-forge, we would either need to get the download package on conda-forge first (https://github.com/conda-forge/staged-recipes#6-do-all-of-my-packages-dependencies-have-to-be-in-conda-forge-already), or remove the dependency on the download package. 

Given that we only use the download package once, to download files, it seems like it would be fairly easy to remove it as a dependency. 

What do you think @lwasser? Would you be comfortable removing the dependency on download, using something from the standard library like requests or urllib instead?

**Comment by lwasser** [comment]
Download is used in the `get_data` method. it's a small package that @choldgraf wrote. We could ask him if he's open to moving it to conda-forge. Or we could find an alternative. What are your thoughts on alternatives for downloading? Or Chris - have you considered porting this to conda-forge?

**Comment by mbjoseph** [comment]
@lwasser there are a few alternatives that we could use to download files (e.g., described [here](https://stackabuse.com/download-files-with-python/)). 

But, if @choldgraf is interested in putting the download package on conda-forge, that would be great. I am happy to help with this process too.

**Comment by choldgraf** [comment]
I unfortunately have no idea how to put something on conda-forge :-(

**Comment by mbjoseph** [comment]
Conda-forge has some instructions here: https://conda-forge.org/#add_recipe

If it was of interest, I could work on submitting the download library to conda-forge and add you as a collaborator on the resulting repo/keep you in the loop on the submission PR. 

Otherwise, we may need to drop the download library as a dependency to get EarthPy deployed to conda-forge. 

What do you think @choldgraf - do you have any interest in getting the download library on conda-forge, and do you want me to help with the submission process?

**Comment by choldgraf** [comment]
one must be possible to specify dependencies that are only installable via `pip` in a conda forge project. People do all kinds of crazy stuff with conda forge, and since conda also ships with pip, it must be possible to say "when you run `conda install earthpy` also run `pip install download`". Did you double check this?

Otherwise, I am happy to try figuring this out

**Comment by mbjoseph** [comment]
I assumed one could include dependencies that were only installable via `pip` too, until I was unable to get earthpy's conda-forge recipe to work, and then read this: https://github.com/conda-forge/staged-recipes#6-do-all-of-my-packages-dependencies-have-to-be-in-conda-forge-already

**Comment by choldgraf** [comment]
sigh. hmm ok I can look into this further, it will be a little bit of time though because I'm a few grant deadlines

**Comment by mbjoseph** [comment]
Thanks @choldgraf - let me know if I can help!

**Comment by mbjoseph** [comment]
EarthPy is now live on conda-forge: https://github.com/conda-forge/earthpy-feedstock

@choldgraf we ended up using requests instead of the download library to get the conda-forge deployment up quickly, due to some issues we were having with conda installation issues across platforms for the teaching environment.

**Comment by choldgraf** [comment]
sounds good to me
