### ISSUE TITLE
File not found error - data issue

### ISSUE THREAD

**Issue by lwasser** [earthlab/earthpy#250]
hey @mbjoseph @joemcglinchy . i just installed earthpy using pip and ran into a data issue:
```
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-1-b7638144e60a> in <module>()
      5 import matplotlib.pyplot as plt
      6 import matplotlib.dates as mdates
----> 7 import earthpy as et
      8 import earthpy.plot as ep
      9 import geopandas as gpd

~/anaconda3/envs/earth-analytics-python/lib/python3.6/site-packages/earthpy/__init__.py in <module>()
     15 
     16 epsg = json.loads(
---> 17     resource_string("earthpy", "example-data/epsg.json").decode("utf-8")
     18 )

~/anaconda3/envs/earth-analytics-python/lib/python3.6/site-packages/pkg_resources/__init__.py in resource_string(self, package_or_requirement, resource_name)
   1146         """Return specified resource as a string"""
   1147         return get_provider(package_or_requirement).get_resource_string(
-> 1148             self, resource_name
   1149         )
   1150 

~/anaconda3/envs/earth-analytics-python/lib/python3.6/site-packages/pkg_resources/__init__.py in get_resource_string(self, manager, resource_name)
   1390 
   1391     def get_resource_string(self, manager, resource_name):
-> 1392         return self._get(self._fn(self.module_path, resource_name))
   1393 
   1394     def has_resource(self, resource_name):

~/anaconda3/envs/earth-analytics-python/lib/python3.6/site-packages/pkg_resources/__init__.py in _get(self, path)
   1513 
   1514     def _get(self, path):
-> 1515         with open(path, 'rb') as stream:
   1516             return stream.read()
   1517 

FileNotFoundError: [Errno 2] No such file or directory: '/Users/lewa8222/anaconda3/envs/earth-analytics-python/lib/python3.6/site-packages/earthpy/example-data/epsg.json'
```

have either of you run into this? i do see that directory is NOT there in my environment.

**Comment by lwasser** [comment]
this could be something specific to my push to pip as i was able to make it work installing from master

**Comment by mbjoseph** [comment]
Looks like a duplicate of https://github.com/earthlab/earthpy/issues/245

Can you try the suggestion that I made in that thread to solve the issue?

**Comment by lwasser** [comment]
it actually works for me when i install from master. it doesn't work from pip. so i can't try the fix because that would have to be pushed to pip! it is a duplicate tho!!

**Comment by mbjoseph** [comment]
If you delete the line `include_package_data=True` from setup.py locally on the master branch, does everything still work for you?

**Comment by lwasser** [comment]
@mbjoseph why do i need to reinstall the entire environment? i just installed and uninstalled earthpy . when i install from pip i get the error. when i install it locally via master branch `-e .` it seems to work. removing that line from `setup.py` doesn't seem to impact the local install.

**Comment by mbjoseph** [comment]
Great - glad to hear that deleting that line still works locally. That's what I suspected based on https://stackoverflow.com/questions/7522250/how-to-include-package-data-with-setuptools-distribute

As far as why to reinstall the whole environment - that probably wasn't 100% necessary but just wanted to be sure that you were working with a fresh installation. I will submit a PR that removes this line, which should solve the problem once we merge it and deploy to PyPI.

**Comment by lwasser** [comment]
closing this as well!!
