### ISSUE TITLE
plot.draw_legend fails when classes provided

### ISSUE THREAD

**Issue by mirob9363** [earthlab/earthpy#253]
**Describe the bug**
The `draw_legend` function is not allowing classes to be passed in. 

**To Reproduce**
Example can be found in Earth Analytics lesson:
https://github.com/earthlab/earth-analytics-lessons/blob/master/courses/earth-analytics-python/08-multispectral-remote-sensing-fire/in-class/2017-03-01-fire02-calculate-NBR-with-landsat-Python.ipynb

**Expected behavior**
Use input classes for legend

**Screenshots**

```
---------------------------------------------------------------------------`
ValueError                                Traceback (most recent call last)
<ipython-input-18-813df5b17d83> in <module>()
     14 ep.draw_legend(im, 
     15                classes=values,
---> 16                titles=dnbr_cat_names)
     17 
     18 

~\AppData\Local\Continuum\anaconda3\envs\earth-analytics-python\lib\site-packages\earthpy\plot.py in draw_legend(im_ax, bbox, titles, cmap, classes)
    479     # If classes not provided, get them from the im array in the ax object
    480     # Else use provided vals
--> 481     if classes:
    482         try:
    483             # Get the colormap from the mpl object
```
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
**What Operating System Are you Running? **
 - Windows

**Comment by mirob9363** [comment]
@lwasser Can you please look at this?

**Comment by lwasser** [comment]
@mirob9363  thank you for this PR!! can you kindly provide a link to a notebook where you IMPLEMENTED the actual `draw_legend()` functionality and it failed so i can look at that? This might mean linking to the notebook on a branch you are working on! 

Thank you

**Comment by lwasser** [comment]
@mirob9363 Also this notebook uses old deprecated earthpy functions. So please do the following

1. update the notebook so that it is using the most current code.
2. Post a link to that and ideally pull out the code that is not running properly and also what error you are getting

Ping me when this is done!

**Comment by mirob9363** [comment]
This example should work (or not work I guess) to demonstrate the issue: 
```
import numpy as np
import earthpy.plot as ep
import matplotlib.pyplot as plt
im_arr = np.random.uniform(-2, 1, (15, 15))
bins = [-np.Inf, -0.8, 0.8, np.Inf]
im_arr_bin = np.digitize(im_arr, bins)
cat_names = ["Class 1", "Class 2", "Class 3"]
values = np.unique(im_arr_bin.ravel())
f, ax = plt.subplots()
im = ax.imshow(im_arr_bin, cmap="gnuplot")
im_ax = ax.imshow(im_arr_bin)
leg_neg = ep.draw_legend(im_ax = im_ax, titles = cat_names, classes=values)
```

**Comment by lwasser** [comment]
this issues should be resolved given the PR was just merged!!  @mirob9363 just a note that draw_legend should work now!! :)

**Comment by mirob9363** [comment]
Great! I'll update and try it out.
