### ISSUE TITLE
plot_bands title parameter not working properly 

### ISSUE THREAD

**Issue by mirob9363** [earthlab/earthpy#258]
**Describe the bug**

`plot.plot_bands` title parameter not working properly. I am using a string input title, but I am getting the following error. 
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-15-8431737ac8e6> in <module>()
      1 title ="NAIP RGB Imagery - Band 1-Red\nCold Springs Fire Scar"
      2 ep.plot_bands(naip_csf[0],
----> 3               title=title)

~\AppData\Local\Continuum\anaconda3\envs\earth-analytics-python\lib\site-packages\earthpy\plot.py in plot_bands(arr, cmap, figsize, cols, title, extent)
    128                 """Plot_bands() expects one title for a single
    129                              band array. You have provided more than one
--> 130                              title."""
    131             )
    132         elif not (len(title) == arr.shape[0]):

ValueError: Plot_bands() expects one title for a single
                             band array. You have provided more than one
                             title.

```

**To Reproduce**
1. Go to [lesson 2](https://github.com/earthlab/earth-analytics-lessons/blob/master/courses/earth-analytics-python/07-multispectral-remote-sensing-in-python/01-multi-spectral-remote-sensing-python/2018-04-14-multispectral02-open-NAIP-imagery-in-python.ipynb) in week 7 Earth Analytics course 
2. Cell i am running uses the following code: 
```
es.plot_bands(naip_csf[0],
              title="NAIP RGB Imagery - Band 1-Red\nCold Springs Fire Scar")
```
**Expected behavior**
The function should plot the red band as a grayscale image. 

**What Operating System Are you Running? **
Windows

**Comment by lwasser** [comment]
Similarly @mirob9363 please link to a notebook that actually has the changed code implemented so I can run it and see what is happening. Alternatively you can provide the code needed to reproduce the error (this is actually more ideal). then i can run it in pycharm without worrying about notebooks.

**Comment by lwasser** [comment]
ok @mirob9363 i was able to reproduce this issue. Here is the code that would have made this issue much easier for me to trouble shoot:

```
import earthpy.plot as ep
import earthpy as et
import rasterio as rio
import os
os.chdir(os.path.join(et.io.HOME, 'earth-analytics'))

with rio.open("data/cold-springs-fire/naip/m_3910505_nw_13_1_20150919/crop/m_3910505_nw_13_1_20150919_crop.tif") as src:
    naip_csf = src.read()
    naip_csf_meta = src.meta

arr = naip_csf[0]
title="NAIP RGB Imagery - Band 1-Red\nCold Springs Fire Scar"
ep.plot_bands(naip_csf[0], title="NAIP RGB Imagery - Band 1-Red\nCold Springs Fire Scar")
```

**Comment by lwasser** [comment]
please see pr: https://github.com/earthlab/earthpy/pull/263

**Comment by lwasser** [comment]
This has been resolved [via this issue](https://github.com/earthlab/earthpy/pull/263)
