### ISSUE TITLE
Do we need earthpy.utils.fix_paths?

### ISSUE THREAD

**Issue by mbjoseph** [earthlab/earthpy#259]
The `fix_paths` function in `earthpy/utils.py` seems like a carry-over from website build logic. Can we remove this from EarthPy?

**Comment by lwasser** [comment]
oh totally. that is a no brainer. i'll submit a PR now!!

**Comment by lwasser** [comment]
Closing this as the PR was just merged!! Thank you for creating this issue @mbjoseph !!!
