### ISSUE TITLE
plot_rgb with masked array returns error on dtype

### ISSUE THREAD

**Issue by joemcglinchy** [earthlab/earthpy#291]
**Describe the bug**
when passing in a 3 band masked array to `earthpy.plot.plot_rgb()` an error is returned regarding dtype of the numpy array not being appropriate.

**To Reproduce**
the following code:

```
import os
from glob import glob
import earthpy as et
import earthpy.spatial as es
import earthpy.plot as ep
import numpy as np
import matplotlib.pyplot as plt

data = et.data.get_data("cs-test-landsat")
os.chdir(os.path.join(et.io.HOME, 'earth-analytics'))

landsat_bands = "data/cs-test-landsat/LC08_L1TP_034032_20160621_20170221_01_T1_sr_band*[2-4]*.tif"
stack_bands = glob(landsat_bands)
stack_bands.sort()
arr, meta = es.stack(stack_bands)
````
`ep.plot_rgb(np.ma.masked_equal(arr, -9999)` returns: ValueError: 3-dimensional arrays must be of dtype unsigned byte, unsigned short, float32 or float64

**Expected behavior**
The array should be plotted with the  nodata areas shown as white (alpha band)

**Screenshots**
n/a

**What Operating System Are you Running? **
 Windows 10

**Additional context**
I think I've identified the source of this value error. This block... 

```# If type is masked array - add alpha channel for plotting
    if ma.is_masked(rgb_bands):
        # Build alpha channel
        mask = ~(np.ma.getmask(rgb_bands[0])) * 255

        # Add the mask to the array & swap the axes order from (bands,
        # rows, columns) to (rows, columns, bands) for plotting
        rgb_bands = np.vstack(
            (es.bytescale(rgb_bands), np.expand_dims(mask, axis=0))
        ).transpose([1, 2, 0])
```
the result of `np.expand_dims(mask, axis=0)` is int32 since the mask is int32. the result of bytescale, however, is uint8 as we would expect, and the result of `np.vstack` is set to int32 because of the mask. Thus, the plotting doesn't work since for a 3 or 4 band (3+alpha channel) since the data type is incorrect for matplotlib.

The fix for this can be to replace the `np.expand_dims(mask, axis=0))` with `np.expand_dims(mask, axis=0)).astype("uint8")`. This looks hacky, but may look better (readable) as:

```
rgb_bands = es.bytescale(rgb_bands)
rgb_bands = np.vstack(rgb_bands, 
                      np.expand_dims(mask, axis=0).astype(rgb_bands.dtype)))
                      .transpose([1, 2, 0])
```

**Comment by lwasser** [comment]
ahhhh @joemcglinchy just out of curiosity are you running earthpy 0.6.4? i can't recreate this issue! but i believe it is likely an issue just can't recreate it.

**Comment by joemcglinchy** [comment]
i am running earthpy 0.6.4, yes.

**Comment by lwasser** [comment]
@joemcglinchy just curious -- is this still an issue after the updates to `plot_rgb()` ??

**Comment by joemcglinchy** [comment]
I will give it a go!

**Comment by lwasser** [comment]
wonderful! and we have bumped the version to 0.6.6  which will have those changes. i'm not sure if it actually fixes your issue ofcourse but worth a try

**Comment by lwasser** [comment]
@joemcglinchy following up on this issue. i haven't been able to recreate it. Is it still a bug with the new version of earthpy? if so are you willing to submit a PR to fix it and a test that will also reproduce it to catch it for future ?

**Comment by joemcglinchy** [comment]
just ran this code, it produces the following with earthpy 0.6.8!

![image](https://user-images.githubusercontent.com/4762214/57385720-2efb2e80-7170-11e9-92a3-722be5698a78.png)

Closing.

**Comment by lwasser** [comment]
awesome!! so glad this is fixed @joemcglinchy  thank you for submitting the issue!!
