### ISSUE TITLE
We need to bump version + UPDATE CHANGE LOG

### ISSUE THREAD

**Issue by lwasser** [earthlab/earthpy#295]
Leah forgot!

**Comment by lwasser** [comment]
conda forge pulls from pypi so i have to release

**Comment by lwasser** [comment]
@mbjoseph  do you want me to bump again now? 
If that get-started PR and the plot-rgb one gets approved we can bump with the new docs and the bug fixes. but if we want to wait i can bump now too!! just lemme know.

**Comment by mbjoseph** [comment]
@lwasser yes it would be great to deploy to PyPI so that we have the README and LICENSE being distributed with the package. Thanks!

**Comment by mbjoseph** [comment]
Solved with https://github.com/earthlab/earthpy/releases/tag/v0.6.6
