### ISSUE TITLE
Specify python version for PyPI uploads

### ISSUE THREAD

**Issue by mbjoseph** [earthlab/earthpy#296]
In the .travis.yml file we do not currently point to any particular python version, which seems to lead to failures e.g., https://travis-ci.org/earthlab/earthpy/builds/511121943

We may need to specify a particular version e.g., https://github.com/earthlab/streamstats/blob/master/.travis.yml#L15-L24

**Comment by lwasser** [comment]
i just added a commit to fix this @mbjoseph see - 2fcb177240a11d3d8af49b50348d89da9fceaea1 i did it directly which is bad form but i can only test deployment here i think??

**Comment by mbjoseph** [comment]
Cool - thanks @lwasser that seems to have fixed it! I see that we have v0.6.5 on PyPI and on our releases page.
