### ISSUE TITLE
Make a custom data folder for the vignettes

### ISSUE THREAD

**Issue by nkorinek** [earthlab/earthpy#309]
Right now, we are using `et.data.get_data()` data for the vignettes, and making it work. However, there are sometimes when this is less then ideal, such as having to use `cs-test-landsat` data, which is mostly intended for private use. If we curated some data just for the vignettes we could simplify them and make the data perfect for our examples.

**Comment by jlpalomino** [comment]
@lwasser @mbjoseph In order to both have nodata values and cover the Cold Springs fire boundary, the resulting cropped Landsat bands are approximately 85 MB. I have placed them on figshare and added the url to DATA_URLS.

**Comment by lwasser** [comment]
@jlpalomino thank you . can you please add a link here to the figshare repo? 
@nkorinek can you please test out the new data subset with your submitted vignette?

**Comment by jlpalomino** [comment]
@nkorinek It may be best to test this by actually adding the following to DATA_URLS in earthpy/io.py: 
```
"vignette-landsat": (
        "https://ndownloader.figshare.com/files/15197123",
        ".",
        "zip",
    ),
```
Then, updating landsat_bands_data_path to ```"data/vignette-landsat/...```.

**Comment by jlpalomino** [comment]
@lwasser  One more thing to consider for the crop data vignette is that the Cold Spring fire boundary is currently in a different figshare repo, the one for "cold-springs-fire".  Would you like me to include this fire boundary in the "vignette-data" repo, so that the vignette uses only one figshare download?

**Comment by lwasser** [comment]
heya @jlpalomino get_data accepts url's now. so nathan can just download using the `url=` parameter and it should work perfectly without updating the actual code of the package!!

**Comment by lwasser** [comment]
yes please include it @jlpalomino  it should all be in the same repo. i get there is some data redundancy but we do want the subsets to be self-contained!!

**Comment by jlpalomino** [comment]
@lwasser Great on both!  The figshare repo has now been updated to include to Cold Springs fire boundary. @nkorinek New URL for updated vignette data: https://ndownloader.figshare.com/files/15197339

**Comment by lwasser** [comment]
woo hoo. thank you @jlpalomino  this is awesome. @nkorinek i believe will be in again tomorrow and can test this out for us. Tell me. Do your vignettes use this subset already? or is there vignette updating that we need to consider implementing given this update?
