### ISSUE TITLE
Create Vignette  -- plot_bands

### ISSUE THREAD

**Issue by lwasser** [earthlab/earthpy#315]
Create a vignette that shows how to use plot bands to 

1. plot multiple bands with one call or 
2. plot a single band with a colorbar with scale turned on or off...

**Comment by lwasser** [comment]
@nkorinek i'd like for you to work on this vignette next! it looks like you are done with the other vignette!!  are you game??

**Comment by nkorinek** [comment]
@lwasser Ya I can totally make this! I'll get started right away.

**Comment by nkorinek** [comment]
Vignette created in [this pr](https://github.com/earthlab/earthpy/pull/321), still needs review!

**Comment by lwasser** [comment]
closing this via this merged pr https://github.com/earthlab/earthpy/pull/321
