### ISSUE TITLE
New Vignette - hillshade

### ISSUE THREAD

**Issue by lwasser** [earthlab/earthpy#329]
@nkorinek please make a new vignette that highlights the hillshade function.

you can use the spatial-vector-lidar data- there are some NEON lidar dem / chm files in there.

What would be cool is to have the final plot be an overlay with a hillshade on the bottom and you could color the canopy height model by height. 

https://www.earthdatascience.org/courses/earth-analytics-python/lidar-raster-data/overlay-raster-maps/

- [x] please add a new link to the readme with the new vignette link
- [x] please create a data subset that we can add to figshare and earthpy with just the data needed for this vignette!! 
- [x] add the data subset link (@lwasser can help you create the link) to earthpy.io

**Comment by nkorinek** [comment]
@lwasser I have the data subset I need but I need to make a link to it and I'm not sure how

**Comment by lwasser** [comment]
@nkorinek please tell me more. 
Are you suggesting that you would like to create a new data subset that we can use for this vignette? So we might add it to earthpy as a key and to figshare as a zip file? IF that is the case i can add it to figshare, give you the link and you can add it to earthpy via a pr!!  i just need the files that you'd like to add!!

**Comment by nkorinek** [comment]
Addressed in this pr: https://github.com/earthlab/earthpy/pull/361

**Comment by lwasser** [comment]
closing given the merged pr. thank you @nkorinek !!!
