### ISSUE TITLE
Write ".tif" generator function - aka the raster iron

### ISSUE THREAD

**Issue by lwasser** [earthlab/earthpy#33]
## Create a tif generator which would have

1. array
2. number of bands 

## Outputs
1. geotiffs

**Comment by joemcglinchy** [comment]
see PR #45 

I edited `test_spatial.py` to add a couple of helper functions to support:

creating 3D arrays where the pixel value for each band is the number of that band createArray
writing a 3D array to a GeoTIFF file on disk

However, seems a few checks didn't pass, so please have a look!

**Comment by mbjoseph** [comment]
Solved by #146
