### ISSUE TITLE
Look at earthpy docs -- are there vignettes that would be helpful / that we should have ?

### ISSUE THREAD

**Issue by lwasser** [earthlab/earthpy#332]
Give the docs a review @nkorinek 
are there workflows that we should capture that would show people functionality in earthpy? 

For example, do we show anything about clip for shapefiles?

**Comment by nkorinek** [comment]
@lwasser like we mentioned in this issue already, we don't have any vignette for the clip functionality of earthpy at all. Do we want that?

We also don't have any vignette that covers `ep.make_col_list()`, `ep.colorbar()`, `es.extent_to_json()`, `es.bytescale()`. These are all rather minor functions, the only one that we might want to try and add into a vignette somewhere would be `ep.colorbar()` in my opinion. Thoughts?

**Comment by lwasser** [comment]
@nkorinek very good point.

Clip we absolutely want to include in the vignettes!! i agree colorbar could be good as well. Do you think colorbar might fit into one of the existing vignettes? possibly the draw legend one?? the other functions are more helper functions - i agree... BUT.. actually extent_to_json could be used in the clip vignette. that was why it was initially created!!

**Comment by lwasser** [comment]
closing this and will open an issue to create a clip vignette
