### ISSUE TITLE
Add Crop all images  function to earthpy

### ISSUE THREAD

**Issue by lwasser** [earthlab/earthpy#333]
function name: 
*  `crop_all`
*****************
* `crop_image_list`
*  `crop_list`
* `crop_images`
*  `crop_allthethings`
* `bulk_crop` or `crop_bulk`
* `crop_all_images`
* `batch_crop` :(
* `sir_crop_a_lot`
* `crop_wad`
****************
this WILL  confuse the user:
so we are creating a new function
```
with rio.open.....as dst:
    crop_image(dst, crop_object)
```

```
crop_image([list-here], crop_object)
```
 so we should create a new function!
****************
it will use: `crop_image`
parameters:

* list of files
* `output dir` -- list or single value -- 
   - output file names with full paths??
   - do we want to allow a list of full paths - we'd want to check the **unique** base paths here.
   - we give the an error message if the dir doesn't exist  -- let's start by being conservative... and ensure they make it or test that it exists...  
* crop boundary
* `overwrite` - for `dst.write` does that parameter exist using the write ?? -- we could have a conditional that checks for if it exists and not write if it doesn't exist... 
* `**kwargs` - you can access any of the parameters that crop_image -- and we should add to crop_image  -- this would then support - things like:  `all_touched= True` <optional, default = True> 

output extension -- do we want to check that the extensions are valid. 

- [ ] ensure the output extension matches the input driver -- 
https://github.com/earthlab/earthpy/blob/master/earthpy/spatial.py#L221
-  [ ] verbose argument (default == False) that provides them with input that things are still processing?? 

return: list of files to stack 
(rather than calling stack within the function)

**Comment by lwasser** [comment]
## Tests for this function
********
* output files are actually created
* they are overwritten or not depending on the parameter value
* a bad working director is flagged - returns an error
* test number of output files
* test that it writes a valid file 
* making sure it fails when the crop_ext is in a diff CRS or the extent don't overlap 
* if we have a verbose argument -- test that the printed output are as expected -- look at the `io` module for how this could be implemented...

**Comment by nkorinek** [comment]
@lwasser @joemcglinchy @jlpalomino @mbjoseph question about this function: what should I do with the metadata returned by crop image? Currently, the function returns a list of paths that point to the images (which is really just the path that the user input in the first place to specify the file names). Should I return the paths in a tuple with the metadata for each image? Should I take one image's metadata return that? Sorry to tag all of you, but I thought you all might have different thoughts on what should be done here.

**Comment by lwasser** [comment]
@nkorinek let's think about this. you are cropping a bunch of images -- and writing them. will it return numpy arrays? because if it doesnt (and maybe it shouldnt), then i think we just want to return a list of paths? if this function simply JUST WRITES out all of the images with the intention of stacking after in a separate this could make sense.

**Comment by nkorinek** [comment]
@lwasser I forgot that `es.stack()` was in the workflow. That will return a rasterio profile which should give access to the metadata object. The function currently returns a list of paths, but the list of paths is one of the inputs for the function. So it feels weird returning the unmodified input. But it makes sense that that's what it would return.

**Comment by lwasser** [comment]
i think so. we could have a `verbose` parameter what a user could use to mute that ouput. but i think telling them where the files are written is a good idea. 

because the default would be `dir/path/path/filename_crop.tif` correct? so it would be useful for them to see "hey i wrote things out here" but then have `verbose = False` as an option to turn that off.

**Comment by nkorinek** [comment]
I could implement the verbose argument! But ya the default would be a list of filepaths that point to the newly created files. It will be identical to the list they provide in the inputs parameter, as we decided we wanted them to supply a list of file names, not a directory. But you're right, I think it does make since for it to return that list again, just workflow wise it makes sense, and then you know that the function did what you expected it to do. Thanks for the advice!

**Comment by lwasser** [comment]
totally @nkorinek i think we might want two sets of options.

1. the user provides a dir_path. in that instance you will return a list of output file names which will deconstruct the original name and append `_crop` 
2. the user provides a list of filenames with a full path. 

Each option has the same function return. however they will be implemented differently depending upon what the user provides. 

Make sense?

**Comment by nkorinek** [comment]
I think that makes sense @lwasser !

**Comment by nkorinek** [comment]
Addressed in this pr: https://github.com/earthlab/earthpy/pull/342

**Comment by nkorinek** [comment]
@lwasser we can probably close this issue now!

**Comment by lwasser** [comment]
oh you are so right!! closing. thank you for all of your work @nkorinek !!!
