### ISSUE TITLE
Add test to stack that all images  have the same transform parameters

### ISSUE THREAD

**Issue by lwasser** [earthlab/earthpy#334]
add another test / functionality that tests in stack that all images have the same "transform" object

hey @joemcglinchy we want to test each image to ensure the transform is the same

**Comment by joemcglinchy** [comment]
Please see #344 . This has updates tests/fixtures and code for:

1) mismatched affine transforms (i.e., more than one unique affine transform in list of sources)
2) mismatched CRS (i.e., more than one unique CRS in list of sources)
3) mismatched image dimensions (i.e., more than one unique set of [rows,cols] in list of sources)

**Comment by lwasser** [comment]
closing this via #344  !!!
