### ISSUE TITLE
Add Nathan to zenodo

### ISSUE THREAD

**Issue by lwasser** [earthlab/earthpy#338]
i'd like to add @nkorinek as a contributor to earthpy

https://github.com/earthlab/earthpy/blob/master/.zenodo.json 

Nathan -- this file needs to be updated for this to happen. Are you game to add yourself ??
@jlpalomino to update this file, should we add roles (i know we have been talking about this).?

**Comment by jlpalomino** [comment]
@lwasser It seems that we decided to have creators and contributors (whose type would be ```Other```; [see example](https://github.com/earthlab/earth-analytics-open-gis-python-workshop/blob/master/.zenodo.json)).  You can see the other contributor types on this [help page](https://help.zenodo.org/guides/search/).

**Comment by nkorinek** [comment]
@lwasser @jlpalomino I'm game to do this, but a quick question first. All of the existing contibutors have an `orcid` value that is unique to all of them. What is this value and where would I find it?

**Comment by lwasser** [comment]
@nkorinek you should create an orcid id for yourself. google it. it will allow you to link ALL of your work to that id rather than worrying about emails and other contact information that changes over time.

**Comment by nkorinek** [comment]
Huh, cool! I've never heard of that. I'll do that, thanks!

**Comment by nkorinek** [comment]
Taken care of in this PR: https://github.com/earthlab/earthpy/pull/339

**Comment by lwasser** [comment]
closing this!!!
