### ISSUE TITLE
Write Unit Test & Update Asserts for crop_image

### ISSUE THREAD

**Issue by lwasser** [earthlab/earthpy#34]

**Comment by mbjoseph** [comment]
Note to whoever writes these tests, please consider the edge case of cropping using an extent that is just a point (with zero area), e.g., something like the result of 

```python
earthpy.spatial.extent_to_json([0, 0, 0, 0]) # [xmin, ymin, xmax, ymax]
```

For completeness, there is also the edge case of when the extent is a line, e.g., 

```python
earthpy.spatial.extent_to_json([0, 0, 1, 0])
```

**Comment by mbjoseph** [comment]
This issue is a duplicate of  #70
