### ISSUE TITLE
Can i remove pandas from dev-requirements?

### ISSUE THREAD

**Issue by lwasser** [earthlab/earthpy#358]
hey @mbjoseph @joemcglinchy it doesn't seem like we need pandas in the dev-requirements as it should install with geopandas and also it's core to anaconda i think?? any thoughts on this? pybot is encouraging me to reduce dependencies via a dozen PR's! 

https://github.com/earthlab/earthpy/blob/master/dev-requirements.txt

any thoughts on removing it?

**Comment by mbjoseph** [comment]
Yeah let's get rid of it!

**Comment by lwasser** [comment]
oh thank goodness for that!! :)
