### ISSUE TITLE
Vignette Update - add crop_image to NDVI vignette

### ISSUE THREAD

**Issue by lwasser** [earthlab/earthpy#368]
LEt's make a few changes to the vignettes and add `crop_image`

1. remove this bullet - `Crop raster bands to a study area` from the readme
2. update `Stack raster bands from data such as Landsat into an easy to use numpy array` to be `Efficiently crop and stack a set of raster files using earthpy`
3. Update [this vignette](https://earthpy.readthedocs.io/en/latest/gallery_vignettes/plot_calculate_classify_ndvi.html#sphx-glr-gallery-vignettes-plot-calculate-classify-ndvi-py) -- crop the image using crop_image to remove the white weird area in the bottom right hand corner 

![image](https://user-images.githubusercontent.com/7649194/59451956-eadff700-8dc9-11e9-86d7-4bcc703f838c.png)

**Comment by nkorinek** [comment]
After looking into this for a while, I've run into some speed bumps I could use some advice for. `es.crop_image()` only takes rasterio object, which in turn have to be created from a tif file. In order to just crop the final NDVI image, I would have to write it out to a geotiff file and then open it with rasterio. Thoughts on this? Do we want to add that into this workflow? @lwasser

**Comment by lwasser** [comment]
@nkorinek why don't you crop the images when they are imported? that makes more sense given we want to work with the smallest dataset possible? then you can calculate NDVI on already cropped images.

**Comment by lwasser** [comment]
this means instead of using `.read()` for each file you import you use `es.crop_image()`

**Comment by nkorinek** [comment]
Looked at in https://github.com/earthlab/earthpy/pull/372

**Comment by nkorinek** [comment]
It's been decided that we are going to add `es.crop_image()` to the `plot_raster_stack_crop` vignette instead, as it matches the vignette's workflow much better, and would be where users are more likely to find it.

**Comment by nkorinek** [comment]
changed pull request to https://github.com/earthlab/earthpy/pull/374
