### ISSUE TITLE
Create Google Doc with a list of functions and current status for tracking 

### ISSUE THREAD

**Issue by lwasser** [earthlab/earthpy#37]
* cleanup of old functions
* google doc ...

**Comment by lwasser** [comment]
giving this to @lherwehe to work on. lauren please place the google doc link here when you have gotten it goin!!

**Comment by lherwehe** [comment]
Hi @lwasser @jlpalomino @mbjoseph & @joemcglinchy -

Here is a google spreadsheet for tracking the functions...
[](https://docs.google.com/spreadsheets/d/1_niZJ19tydYclwv_Sub0RRECPnWWUxynpWNR8N5Nbwg/edit#gid=0)

**Comment by lwasser** [comment]
This is great. thank you @lherwehe !!!

**Comment by lwasser** [comment]
closing this issue as we have resolved everything in the google doc at this point!!
