### ISSUE TITLE
Create Clip vignette and potentially a small data subset that can be clipped

### ISSUE THREAD

**Issue by lwasser** [earthlab/earthpy#378]
Please create a new vignette that demonstrates the clip functionality in earthpy (clipping vector data).

**Comment by nkorinek** [comment]
@lwasser Hey, quick question! When we were talking about creating a clip vignette, you mentioned we could incorporate `es.extent_to_json()` in the clip vignette. I've been having issues with this, as `ec.clip_shp()` doesn't accept arguements that aren't GeoPandas objects. After reviewing the documentation for `es.extent_to_json()`, I believe it was meant to be used with raster cropping, not vector clipping. Am I understanding this wrong? If it was meant for raster cropping, should I try and add it into that vignette instead? Thanks!

**Comment by lwasser** [comment]
@nkorinek i believe you are correct. don't worry about incorporating that function. just focus on clipping points, lines and polygons!! :)

**Comment by lwasser** [comment]
@nkorinek i just had a look at the clip vignette again. i noticed that it only clips lines and does not clip points of polygons. can you please update it to demonstrate all three? If in that process if we need to create a new dataset with all three that is smaller, let's do that.

**Comment by lwasser** [comment]
Let's hold off on this until i clarify with joris about handing the data

https://github.com/geopandas/geopandas/issues/821

**Comment by lwasser** [comment]
closing this given CLIP is now in geopandas and we don't need this in earthpy
