### ISSUE TITLE
Add thumbnails to the plot bands and plot histograms vignettes

### ISSUE THREAD

**Issue by nkorinek** [earthlab/earthpy#381]
Hey @lwasser ! While looking at the documentation available on read the docs, I noticed that somehow the vignettes for plot bands and plot histograms don't have thumbnails. It would be a really easy fix, I was wondering if I could make a quick PR that would add thumbnails to these vignettes?

**Comment by nkorinek** [comment]
After looking into this a bit more, I actually have a few questions. I noticed that both of these vignettes had `# sphinx_gallery_thumbnail_number = 5` above a plot in the code, but no thumbnail shows up for them. After looking around, I also noticed that vignettes such as plot rgb and draw legend don't have that line of code in them at all, but still have thumbnails on the readthedocs page. Any guesses as to what went wrong with those two vignettes? I realize this isn't high priority right now, I'm just curious. Thanks!

**Comment by lwasser** [comment]
hmmmm i'm not sure why a thumnail would not render @nkorinek let's look at this more closely next week !!?

**Comment by lwasser** [comment]
i just noticed @nkorinek that there are no thumbnails for a bunch of the vignettes now. 

https://earthpy.readthedocs.io/en/latest/gallery_vignettes/index.html

let's see if we can clean this up when you are back!!

**Comment by lwasser** [comment]
my suspicion as to why this isn't working is:

`# sphinx_gallery_thumbnail_number = 5`

the number here refers to the plot number in the vignette. i think it was set to 5 when there weren't 5 plots in the vignette to begin with. if after the docs render that thumbnail appears, @nkorinek that is the fix for all of the vignettes!!

**Comment by lwasser** [comment]
this has been fixed!!!

https://earthpy.readthedocs.io/en/latest/gallery_vignettes/index.html
