### ISSUE TITLE
Fix recursive issue with colorado-flood data

### ISSUE THREAD

**Issue by nkorinek** [earthlab/earthpy#387]
When `et.data.get_data("colorado-flood")` is called, it downloads the data within two recursed "colorado-flood" folders. There should only be one folder that contains the data. @lwasser

**Comment by lwasser** [comment]
ok i shoulda updated the changelog. this should be fixed now but lemme update the change log now!!

**Comment by lwasser** [comment]
pr #388

**Comment by nkorinek** [comment]
@lwasser I just checked that this issue has been updated on my pc, and it works fine! This issue can be closed now.

**Comment by lwasser** [comment]
awesome! thanks @nkorinek  closign now!!
