### ISSUE TITLE
Explain relationship that earthpy has or doesn't have to commercial software?

### ISSUE THREAD

**Issue by sgillies** [earthlab/earthpy#433]
Earthpy explains its relationship to lower-level open source packages like rasterio and geopandas well: it builds on top of them to make some common tasks easier and gives its user more leverage. In reviewing earthpy for https://github.com/pyOpenSci/software-review/issues/3 I wonder if earthpy needs or doesn't need to explain how it relates to commercial software widely used in the higher ed research and teaching domain? This question is not loaded, I promise! 

@lwasser if you don't think this needs to be added to the README, just say so, you are much more of an expert in the teaching field, and I will tick the box in the review.

**Comment by lwasser** [comment]
hi @sgillies !! this is a great question and i'd love to better understand what you are thinking!

What types of commercial software are you thinking about? Like GIS type GUI based tools ??

We modeled earthpy after the `raster` and `sp` packages in `R`. These tools made is a lot easier to handle spatial manipulations in the R language that that didn't' seem to exist for python! 

As far are commercial software that may be related - i am not sure what tools I would call attention to but i'm very open to suggestions if you had any in mind!! i'm not adverse to updating the readme if it would make the goal of our package more clear. @joemcglinchy @mbjoseph @jlpalomino  can you have a look at this issue and see what you think about other packages that might put earthpy into better context? The R tools are the ones that come to mind for me.

**Comment by sgillies** [comment]
@lwasser I think it would be very good if the R packages this is modeled after were mentioned, and if I read the intent of the package correctly, that earthpy is intended for interactive use in a notebook. If earthpy wasn't meant to replace or integrate with commercial software, then no need to mention any.

**Comment by mbjoseph** [comment]
Hi @sgillies and @lwasser! Some thoughts here: 

- I agree we should mention the R packages that inspired EarthPy. Both `raster` and `sp` are wrappers around lower level libraries, but provide a higher level of abstraction, which makes them a bit less flexible but perhaps easier to use for beginners. EarthPy is similar in this sense.
- We tend to use EarthPy in notebooks (in the classroom), but it will work in scripts as well. We don't (AFAIK) have any functionality that is directly tied to a notebook execution environment.
- EarthPy isn't intended to integrate with or replace any particular commercial GIS software in general, so I'd lean towards not mentioning it.

Thanks @sgillies for a thoughtful/comprehensive review! We really appreciate it.

**Comment by lwasser** [comment]
ok i have a PR open and i'll add a bit more text to the readme about the inspiration for earthpy as it aligns with the R packages!!

**Comment by lwasser** [comment]
this has been merged!! if you are not satisfied with the changes @sgillies please reopen this issue or i'm happy to do so and work on it a bit more!!
