### ISSUE TITLE
Within et.data.get_data(), consider using Python's logging instead of print()

### ISSUE THREAD

**Issue by sgillies** [earthlab/earthpy#434]
Context: https://github.com/pyOpenSci/software-review/issues/3

When get_data() is called, text is printed to stdout.

```
>>> data_path = et.data.get_data("vignette-landsat")
Downloading from https://ndownloader.figshare.com/files/15197339
Extracted output to /Users/seang/earth-analytics/data/vignette-landsat/.
```

On the one hand, some feedback to users is a good thing. On the other hand, library functions should avoid printing to stdout and should use Python's logging facility instead so that users have more control over the output.

**Comment by sgillies** [comment]
That said, I scanned the package and this is the only use of print that I could find. If earthpy is mostly for interactive active use in a notebook and not for developing non-interactive programs, calling print from get_data is harmless. Feel free to close this one.

**Comment by lwasser** [comment]
hey @sgillies yes we mostly intend get_data to be used in an interactive environment.  so perhaps we shouldn't modify this now but note that in the future if users want to use it more in a non interactive environment, we may want to get rid of the print statements? 

the other option is to set `verbose=False` for non interactive applications? is that bad practice?

**Comment by sgillies** [comment]
The option is good, but logging (where the default stream is stderr) would be even better. The situation that we want to prevent is where someone writes a script with earthpy that prints data to stdout (used like `python myscript.py > data.geojson`) and it has data download messages interleaved with the JSON text output.

**Comment by lwasser** [comment]
thank you again, @sgillies ok i did some reading on this and started a PR 

https://github.com/earthlab/earthpy/pull/448 

does this approach seem reasonable? OR what would you implement here? in this case i printed if `verbose=True` (which is a default) but used `logging.info` if it's false. Please know this particular concept is new to me SO if i am implementing it incorrectly please do say the word or suggest another approach!!!

**Comment by sgillies** [comment]
@nkorinek yes, changing the log level within the function is a good approach. Instead of configuring the root logger, I think the project should set the level of the module's logger `logging.getLogger(__name__).setLevel(logging.INFO)`. This will increase earthpy's verbosity only and not add noise from requests or other modules.

**Comment by nkorinek** [comment]
@sgillies that looks much cleaner, cool!

**Comment by lwasser** [comment]
ok thank you again for this suggestion @sgillies  for the time being i'm going to close this and the associated PR. but perhaps we will revisit it in the future if it becomes a real problem for people using the package!! your input and review has been greatly appreciated!! THANK YOU!
