### ISSUE TITLE
Consider a more specific/unique directory for tutorial data

### ISSUE THREAD

**Issue by sgillies** [earthlab/earthpy#435]
Context: https://github.com/pyOpenSci/software-review/issues/3.

Downloaded tutorial data is saved to a `earth-analytics/data` directory in the user's home directory.

```python
>>> data_path = et.data.get_data("vignette-landsat")
Downloading from https://ndownloader.figshare.com/files/15197339
Extracted output to /Users/seang/earth-analytics/data/vignette-landsat/.
>>> data_path
'/Users/seang/earth-analytics/data/vignette-landsat/.'
```
An `~/.earthpy` directory would be more like other projects like pip, which creates a `~/.pip` directory on OS X.

**Comment by lwasser** [comment]
hey there @sgillies !!! all of this feedback is so helpful.
In this particular case, we have a teaching application where we are trying to teach students to manage data on their computers. so we have everyone setup a structure that is `earth-analytics/data`. we also have a lesson portal (earthdatascience.org) where lots of people go and work through our lessons... having  `get_data` create the intended structure for students avoids many challenges that they face of creating paths! 

we like to teach about expressive names and keeping data together in a data dir and such. given that explanation, does that structure make a bit more sense? i'm a little concerned about changing this particular item given our teaching applications. Please let me know what you think!!

again I am so appreciative of your input and review!!

**Comment by sgillies** [comment]
@lwasser showing students how to organize their data is a great goal. I only wanted to point out that ~/.earthpy is a bit more safe from being clobbered by other software, security by obscurity. It could be too obscure, though. I don't think this issue is a blocker at all, so feel free to close it up if you like.

**Comment by lwasser** [comment]
got ya @sgillies i appreciate this. i think for this particular application in our classes it might be best to stick with that path. but i hear you on the safety issue and will definitely consider it!! if you are ok with my closing this particular issue, i will. again i'm so thankful for all of this input. i'm learning a lot!!
