### ISSUE TITLE
Change hillshade's keyword arguments to azimuth and altitude?

### ISSUE THREAD

**Issue by sgillies** [earthlab/earthpy#436]
Context: https://github.com/pyOpenSci/software-review/issues/3.

Could the keyword arguments of https://github.com/earthlab/earthpy/blob/16b428827415453c654cc93a366f356a42c9d3c7/earthpy/spatial.py#L559 be made more consistent by changing them to azimuth and altitude and dropping the `angle_` prefix for the latter?

**Comment by lwasser** [comment]
totally @sgillies we can do that!! i'm going to allocate some time today and tomorrow to work on these issues!!

**Comment by lwasser** [comment]
this has been implemented @sgillies !! closing but please reopen if our implementation is not what you intended!! #438 addresses this.
