### ISSUE TITLE
Reconsider exceptions raised in validating clip_shp args

### ISSUE THREAD

**Issue by sgillies** [earthlab/earthpy#437]
Context: https://github.com/pyOpenSci/software-review/issues/3.

In clip.py:clip_shp, the two args are validated in this way:

```python
    try:
        shp.geometry
        clip_obj.geometry
    except AttributeError:
        raise AttributeError(
            "Please make sure that your input and clip GeoDataFrames have a"
            " valid geometry column"
        )
 ```

One school of thought (see Brett Slatkin’s Effective Python) is that earthpy should raise a package-specific exception here where the error arises from improper earthpy usage. Something like

```python
if not isinstance(shp, GeoDataFrame):
    raise EarthpyTypeError(“earthpy requires shp to be a GeoDataFrame”)
if not hasattr(shp, “geometry”):
    raise EarthpyValueError(“earthpy requires shp to have a geometry column”)
```

Alternatively, raise TypeError from the first test and ValueError from the second.

**Comment by lwasser** [comment]
oh interesting!! We are submitting this clip module now to geopandas: https://github.com/geopandas/geopandas/pull/1128 so i think we should definitely consider this in that PR!! we will remove it from here once they merge but i and @nkorinek are still working on the pr.

I will make sure this is addressed in that PR however so will leave this open for the time being!

**Comment by lwasser** [comment]
We have officially moved clip to geopandas and its active in version .7!! Closing this. Thank you again @sgillies for your review and input!!!
