### ISSUE TITLE
[pyOpenSci] Citation details

### ISSUE THREAD

**Issue by HaoZeke** [earthlab/earthpy#443]
# Citation
This is part of https://github.com/pyOpenSci/software-review/issues/3.
I note that the code currently has a zenodo doi. So it would be pertinent to add a bibtex formatted citation in the readme.

**Comment by lwasser** [comment]
i've added a link to the bibtext format in the readme!! i didn't want to copy the citation verbatim in case someone wanted to cite a particular version. please let me know what you think. closing but please reopen if you are not satisfied @HaoZeke !!!
