### ISSUE TITLE
plot bands by default scales the data -- this is pretty annoying in general so we should consider the most common use case.

### ISSUE THREAD

**Issue by lwasser** [earthlab/earthpy#487]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**What Operating System Are you Running? **
 - Mac
 - Windows
 - Linux

**Additional context**

**Comment by nkorinek** [comment]
Fixed here #523 once merged. Also, I think you left the default bug template in this issue on accident @lwasser !

**Comment by lwasser** [comment]
closing as this is merged

**Comment by lwasser** [comment]
closing via #523
