### ISSUE TITLE
Add missing doc strings to the clip_points and clip_line_poly functions

### ISSUE THREAD

**Issue by mcshanec** [earthlab/earthpy#49]
## Identify the Documentation Element That You Propose to Update
I would like to add documentation to two functions: clip_points and clip_line_poly. Currently there is no documentation describing the functions or the arguments. Both files found in clip.py.

## Please Identify Your Proposed Changes Below
I would like to add a description of the function and a description of each argument in each function. Ensuring that PEP8 is used throughout function. Adding a statement on where and how each argument is used.

**Comment by jlpalomino** [comment]
@mcshanec Your issue has been approved. Once you have made your changes, please submit a pull request (PR) with a tag to this issue.

**Comment by lwasser** [comment]
@mcshanec  this is a good issue but in the future place be more specific. As a package maintainer, I am a bit unsure as to whether you are updating docstrings OR the .rst files containing package docs for `readthedocs.io` no addition work needed here as this has been approved already but please try to  be more specific in the future as other projects will ask this of you!

**Comment by jlpalomino** [comment]
@mcshanec  Very good point by Leah. Apologies for not catching that. It would be great if you could update this title (e.g. Missing docstrings for clip_points and clip_line_poly functions).

**Comment by lwasser** [comment]
phew! closing this one. Thank you both @mcshanec  @jlpalomino
