### ISSUE TITLE
Stack() doesn't mask array when a file path is provided

### ISSUE THREAD

**Issue by lwasser** [earthlab/earthpy#493]
**Describe the bug**
This is really weird. in the [week 6 demo notebook](https://github.com/earthlab-education/spring-2020-course-notebooks/blob/master/in-class-demos/wk06-multispectral-remote-sensing-demo.ipynb), when you provide an output path for stack it does NOT return a masked array. But when you do provide a path it DOES return a masked array. This is not the expected behavior.

**To Reproduce**

**Expected behavior**

**Screenshots**

**What Operating System Are you Running? **
 - Mac
 - Windows
 - Linux

**Additional context**

**Comment by nkorinek** [comment]
This issue was confusing me, so I made a gist to describe why I am confused, here: https://gist.github.com/nkorinek/655d590da99b5f26dca8b02208599aea. @lwasser let me know if the gist makes sense? I'll put in the fix suggested if you give the go ahead

**Comment by lwasser** [comment]
please go ahead and implement this fix!

**Comment by lwasser** [comment]
closing this as it was addressed in #525
