### ISSUE TITLE
Docstring documentation missing from clip_shp and RST documentation missing for clip_points

### ISSUE THREAD

**Issue by mlevis1** [earthlab/earthpy#50]
## Identify the Documentation Element That You Propose to Update
clip_shp function in clip.py needs documentation, and clip_point function needs RST documentation.
## Please Identify Your Proposed Changes Below
Add docstring documentation to clip_shp and remove commented out code from crop_image

**Comment by mlevis1** [comment]
This change has been implemented. Please see this pull request:
https://github.com/earthlab/earthpy/pull/78

**Comment by lwasser** [comment]
@jlpalomino  can this issue be closed? if so please attach the PR to it, remove the pr requested tag and then close it!

**Comment by jlpalomino** [comment]
Fixed by #78
