### ISSUE TITLE
earthpy not installed via pip

### ISSUE THREAD

**Issue by rlzijdeman** [earthlab/earthpy#507]
**Describe the bug**
Using `pip install earthpy` or `pip install earthpy --upgrade` I get the following error:
```
xxx@xxx-mbp-2 gisPython % pip install earthpy --upgrade
Collecting earthpy
  Using cached earthpy-0.8.0.tar.gz (1.4 MB)
Requirement already satisfied, skipping upgrade: geopandas in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from earthpy) (0.7.0)
Requirement already satisfied, skipping upgrade: matplotlib>=2.0.0 in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from earthpy) (3.2.1)
Requirement already satisfied, skipping upgrade: numpy>=1.14.0 in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from earthpy) (1.18.2)
Requirement already satisfied, skipping upgrade: rasterio in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from earthpy) (1.1.3)
Collecting Rtree>=0.8
  Using cached Rtree-0.9.4.tar.gz (62 kB)
    ERROR: Command errored out with exit status 1:
     command: /Library/Frameworks/Python.framework/Versions/3.8/bin/python3.8 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/zr/vrpsbc0104v_k5nx4dnhpt580000gn/T/pip-install-p57jsw00/Rtree/setup.py'"'"'; __file__='"'"'/private/var/folders/zr/vrpsbc0104v_k5nx4dnhpt580000gn/T/pip-install-p57jsw00/Rtree/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/zr/vrpsbc0104v_k5nx4dnhpt580000gn/T/pip-install-p57jsw00/Rtree/pip-egg-info
         cwd: /private/var/folders/zr/vrpsbc0104v_k5nx4dnhpt580000gn/T/pip-install-p57jsw00/Rtree/
    Complete output (15 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/zr/vrpsbc0104v_k5nx4dnhpt580000gn/T/pip-install-p57jsw00/Rtree/setup.py", line 3, in <module>
        import rtree
      File "/private/var/folders/zr/vrpsbc0104v_k5nx4dnhpt580000gn/T/pip-install-p57jsw00/Rtree/rtree/__init__.py", line 1, in <module>
        from .index import Rtree
      File "/private/var/folders/zr/vrpsbc0104v_k5nx4dnhpt580000gn/T/pip-install-p57jsw00/Rtree/rtree/index.py", line 6, in <module>
        from . import core
      File "/private/var/folders/zr/vrpsbc0104v_k5nx4dnhpt580000gn/T/pip-install-p57jsw00/Rtree/rtree/core.py", line 143, in <module>
        rt.Error_GetLastErrorNum.restype = ctypes.c_int
      File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/ctypes/__init__.py", line 382, in __getattr__
        func = self.__getitem__(name)
      File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/ctypes/__init__.py", line 387, in __getitem__
        func = self._FuncPtr((name_or_ordinal, self))
    AttributeError: dlsym(RTLD_DEFAULT, Error_GetLastErrorNum): symbol not found
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```
**To Reproduce**
pip 20.0.2 from /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pip (python 3.8)

**Expected behavior**
I have read the recommendation to use Anaconda. I am reluctant to install that because it. will lead to various versions of Python on my machine and I'm uncertain how to access which one. I would expect pip to work (i.e. install the library).

**What Operating System Are you Running? **
macOS Catalina 10.15.3

**Additional context**
Pip and Python version:
`pip 20.0.2 from /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pip (python 3.8)`

**Comment by lwasser** [comment]
hi @rlzijdeman i'll try to reproduce this locally but we do not support pip installations of earthpy. the spatial libraries are complex and GDAL often yields errors when using pypi. let me see however if i can reproduce what you are getting above on my mac.

**Comment by lwasser** [comment]
@rlzijdeman can you please do the following:

run conda info and provide the output here.

then run conda list and provide the output here.

that error interestingly enough looks like it's related to python 2.x which does not support the encoding parameter in the setup file. I'm just curious what your environment looks like now. 

Also can you provide the output of 

`which python` in bash

and when you type python to access the command line - does it say python 2.x or 3.x ?i'm just wondering if you have a python version mismatch

**Comment by lwasser** [comment]
i may see the issue. it's actually not earthpy it's rtree that is difficult to install via pip. we may be able to remove it from the setup which should fix your install. let me do a bit more testing here but we may be able to simply remove this dependency altogether. geopandas does not require it.

**Comment by lwasser** [comment]
ok @rlzijdeman we actually had an open task of deprecating the functions that require rtree which was causing this failure via pip. rtree doesn't install nicely with pip. i just released a new version that has these changes and it should install properly with pip. please git it a try. we are testing it on our end now as well.

**Comment by lwasser** [comment]
@mbjoseph @nkorinek if you do have a chance to test, can you kindly reply here if it seems to work for you in a fresh envt?

**Comment by nkorinek** [comment]
@lwasser can do! Works for me installing it on a clean `conda` environment on Ubuntu.

**Comment by lwasser** [comment]
thank you so much @nkorinek it looks like we have 3 successful installs on MAC and LINUX!!

**Comment by rlzijdeman** [comment]
Dear @lwasser,

Sorry for the delay in response. I wouldn't have been able to provide the conda info, as I don't have it installed. I am running both Python2 and Python3 (which may link to your suspicion of it being a Python 2 related error).

Anyway, the more important 'news' is that because of your fast and efficient handling, you can now add another successful install on MAC!!! Thank you very much!!! 

All the best to you and the team,

Richard

**Comment by lwasser** [comment]
awesome @rlzijdeman so glad it worked for you!!!
