### ISSUE TITLE
Adding new argument to spatial-raster.rst and changing comments in Spatial.py to PEP8 format

### ISSUE THREAD

**Issue by willskor** [earthlab/earthpy#51]
## Identify the Documentation Element That You Propose to Update
1. the spatial-raster.rst file is missing a parameter. 

2. Spatial.py has a lot of code that needs to be put in PEP8 format. Comments don't start with capitalized first letter, some comments are notes to other contributors and should be rephrased to be a "to do" instead of a comment to oneself.

## Please Identify Your Proposed Changes Below
1. The arr_out function is not in the .rst file but it is in the spatial.py file.

2. Starting letter in comments are not capitalized. Comments can also be more clear.
This comment should be rephrased. 
https://github.com/earthlab/earthpy/blob/master/earthpy/spatial.py#L66
This comment referencing an issue with the "current" matplotlib but does not specify what the current matplotlib is.
https://github.com/earthlab/earthpy/blob/master/earthpy/spatial.py#L252
This comment should be changed
https://github.com/earthlab/earthpy/blob/master/earthpy/spatial.py#L345

**Comment by willskor** [comment]
Updated issue 2 to be more clear.

**Comment by mbjoseph** [comment]
Hello @willskor! Thanks for opening this issue. See below for some details: 

1. This is great. I am also noticing that the `arr_out` argument is not described in the docstring for `stack_raster_tifs`. https://github.com/earthlab/earthpy/blob/master/earthpy/spatial.py#L71-L78 

If you can add a description of what the `arr_out` argument expects and what it does to both the `spatial-raster.rst` file and the `earthpy/spatial.py` file, that would be awesome!

2. This sounds good. I would recommend formatting the comments to match PEP 8, and changing the comments to be something like:

https://github.com/earthlab/earthpy/blob/master/earthpy/spatial.py#L66 changes to

```python
# TODO: include a no data value here if provided ...
```

https://github.com/earthlab/earthpy/blob/master/earthpy/spatial.py#L252-L253 changes to

```python
# TODO: verify colorbar works with the latest matplotlib, and is not too wide
```

I would just delete these two comments: https://github.com/earthlab/earthpy/blob/master/earthpy/spatial.py#L344-L345 The first comment is redundant with the docstring for `plot_rgb`, and the second comment seems to be more of an internal dialogue from the developer, that doesn't need to persist in the source code. 

When you submit your pull request, please "@" me by including @mbjoseph in the pull request description. Thanks!

**Comment by willskor** [comment]
Thanks matt, will do!
One last thing. I'm also confused about this comment: https://github.com/earthlab/earthpy/blob/master/earthpy/spatial.py#L65
I'm not sure what it is referring to.

**Comment by mbjoseph** [comment]
I think you can go ahead and delete https://github.com/earthlab/earthpy/blob/master/earthpy/spatial.py#L65

For https://github.com/earthlab/earthpy/blob/master/earthpy/spatial.py#L441, it would be great if you could replace the existing comment with: 

```python
# TODO: write test case for just one color
```

Thanks @willskor!

**Comment by mbjoseph** [comment]
Solved by https://github.com/earthlab/earthpy/pull/68
