### ISSUE TITLE
Reorder the libraries in utils.py and delete commented out code from _init_.py

### ISSUE THREAD

**Issue by katysill** [earthlab/earthpy#52]
## Identify the Documentation Element That You Propose to Update
utils.py is not following pep8 conventions in regards to the order of imported libraries.
There is some code that has been commented out in \_init_.py.

## Please Identify Your Proposed Changes Below
I will reorder the order of libraries being imported in utils.py following pep8 conventions.
I will delete the commented out code from \_init_.py

**Comment by jlpalomino** [comment]
@katysill Your issue has been approved. Once you have made your changes, please submit a pull request (PR) with a tag to this issue.

**Comment by jlpalomino** [comment]
This issue has been resolved by this merged PR: https://github.com/earthlab/earthpy/pull/65.
