### ISSUE TITLE
(1) Remove commented shp_sub line from earthpy/clip.py & (2) add .DS_Store to .gitignore file

### ISSUE THREAD

**Issue by annaspiers** [earthlab/earthpy#53]
## Identify the Documentation Element That You Propose to Update
Line 32 in earthpy/clip.py defines `shp_sub`, but is commented out with an alternative line of code below that defines object.  This commented out line will not be used and should be removed (penultimate line below)

    # Get a list of id's for each road line that overlaps the bounding box and subset the data to just those lines`
    sidx = list(spatial_index.intersection(bbox))
    #shp_sub = shp[shp.index.isin(sidx)]
    shp_sub = shp.iloc[sidx]

## Please Identify Your Proposed Changes Below
Remove line 32

    # Get a list of id's for each road line that overlaps the bounding box and subset the data to just those lines`
    sidx = list(spatial_index.intersection(bbox))
    shp_sub = shp.iloc[sidx]

## Identify the Documentation Element That You Propose to Update
Earth Analytics class repository 
## Please Identify Your Proposed Changes Below
Add .DS_Store to .gitignore file on Earth Analytics class repository

**Comment by lwasser** [comment]
@annaspiers do you have a second submission as  well somewhere? you should have submitted a proposal for two distinct changes.

**Comment by annaspiers** [comment]
Woops, I forgot to keep the WIP at the beginning. Still working on it.

**Comment by lwasser** [comment]
@annaspiers  this looks good. please submit a pull request! I appreciate you updating the gitignore file!!

**Comment by lwasser** [comment]
don't forget to "tag" me when you submit your PR @annaspiers ! like this @lwasser

**Comment by lwasser** [comment]
This has been resolved!
