### ISSUE TITLE
Spatial.py edit documentation and import libraries to pep8 guidelines; suggest code edit for normalized_diff & stack_raster_tifs 

### ISSUE THREAD

**Issue by shwh2628** [earthlab/earthpy#54]
## Identify the Documentation Element That You Propose to Update
Edit the documentation to match pep8 guidelines and rearrange the import libraries to follow pep8 guidelines wherein more general libraries are listed first and more specific libraries after. 

Also delete comments that seem unnecessary, and add comments to suggest a change to normalized_diff function to make it less confusing 

## Please Identify Your Proposed Changes Below

**Documentation should begin with a space and follow with a capital letter (i.e ' # Comment here')**

**Importing should begin with the most general libraries first**

**Delete comments such as**
1.)  #ndvi[np.isnan(ndvi)] = 0 *: commented out in normalized_diff function*
2.) # Should this wrap around show instead of plotting as it does? *: commented in plot_rgb*
3.)  #ax.set(xticks=[], yticks=[]) *:commented out in the hist function*

**Add comments**
1.) For normalized_diff function to suggest a change ( # Could be confusing if one does not know that b2 is subtracted from b1. 
#An individual might assume the first input is subtracted from the second. 
#For example, it could be more commonly assumed : (b1-b2)/(b1+b2) ) 

2.) Add comment for stack_raster_tifs function to include .sort()

**Comment by lwasser** [comment]
very good start to this issue @shwh2628 . IN the future please consider being a bit more specific. Rather than saying Documentation should begin with a space, specify that you editing comment syntax. And provide an example from the file of the type of thing you plan to change. Please go ahead and implement these changes however via a PR.
