### ISSUE TITLE
[WIP] Add missing comments to hist, hillshade, and draw-legend functions in spatial.py 

### ISSUE THREAD

**Issue by hdumke** [earthlab/earthpy#56]
Issue 1: Fix capitalization issues throughout spatial.py so that first word is capitalized and there is a space after the pound sign.
Issue 2: Remove extraneous lines that are commented out from io.py

**Comment by willskor** [comment]
This issue is similar to my issue here: https://github.com/earthlab/earthpy/issues/51
We discussed doing different issues associated with spatial.py.
