### ISSUE TITLE
Do .rst documentation for clip_shp function in clip.py and .rst documenation for normalized_diff function in spatial.py

### ISSUE THREAD

**Issue by windnage** [earthlab/earthpy#57]
## Identify the Documentation Element That You Propose to Update
* The .rst documentation for the clip_shp function is missing. 
* The .rst documentation for the normalized_diff function is missing.  

## Please Identify Your Proposed Changes Below
I propose adding this .rst documentation for both functions identified above.

**Comment by lwasser** [comment]
great submission @windnage . please move forward with submitting a PR with these changes!

**Comment by lwasser** [comment]
This has been merged and the issue is now resolved!
