### ISSUE TITLE
matplotlib vs matplotlib-base as dep

### ISSUE THREAD

**Issue by lwasser** [earthlab/earthpy#571]
conda-forge is suggesting that we depend upon matplotlib-base rather than matplotlib if we don't need pyqt

https://github.com/conda-forge/earthpy-feedstock/pull/12

i just want to do a bit of research. before implementing this!

**Comment by Anthchirp** [comment]
to clarify: this just concerns the conda-forge dependency inside the conda-forge recipe (meta.yaml in the feedstock repository).

The actual python package (ie. this repository) should continue to stay on matplotlib, and there are no changes required here.

The difference between the conda-forge packages 'matplotlib' and 'matplotlib-base' is that the former includes the latter, but it also introduces an additional dependency on pyqt. So unless you also need pyqt to be present you can just move to matplotlib-base and merge the linked pull request. This will mean that anyone who just wants to install earthpy using conda doesn't have to also install pyqt.

**Comment by lwasser** [comment]
AHHHH ok I w ill go ahead and merge this. @nkorinek i believe we can  merge this on conda forge safely and will do so and close this open issue. closing now as it has been merged.
