### ISSUE TITLE
Let's drop support of python 3.5 and add 3.8

### ISSUE THREAD

**Issue by lwasser** [earthlab/earthpy#602]
i'm noticing that we are still supporting 3.5 but there are MANY dependency conflicts associated with it now. let's drop 3.5 so our dependencies can get updated. And we should add 3.8 as we are teaching with it now.

@nkorinek  i'm going to add this as a task for you in asana. i can help in case you haven't worked with tox and travis and such before... i think this fix will make the dependency updates easier. if it works here we can do it in matplotcheck and abc-classroom too.

**Comment by nkorinek** [comment]
Sounds good!

**Comment by lwasser** [comment]
closing this via #603 !! yay @nkorinek  nice work. closign this... let's remember to close all of the outdated PR's next week!! happy friday!
