### ISSUE TITLE
Correct spelling, reword content in spatial-raster.rst and Add summary description of earthpy to index.rst

### ISSUE THREAD

**Issue by mcosmos12** [earthlab/earthpy#61]
#### spatial-raster.rst
1. Correct spelling in Line 16. Misspelled word in BOLD text:
`All files in the list must be in the same Coordinate **Refenence** System (CRS) and`

2. Reword content to better flow below: 

```
   The stack_raster_tifs function takes a list of raster paths and turns that list into an

        1.  a stacked geotiff on your hard drive and
        2.  (optionally) an output raster stack in numpy format with associated metadata.
```

#### index.rst
3. Add documentation that describes the purpose of this file. It seems to follow Sphinx (Python Documentation Generator) 
http://www.sphinx-doc.org/en/1.6/markup/toctree.html

## Please Identify Your Proposed Changes Below
Correction made in BOLD text for spatial-raster.rst:
1. All files in the list must be in the same Coordinate **Reference** System (CRS) and

2. 
   The stack_raster_tifs function takes a list of raster paths and turns **the** list **into the following:** 

     1.  a stacked geotiff on your **local** hard drive and
     2.  **(optional)** an output raster stack in numpy format with associated metadata.

3. 
Use the Sphinx documentation to describe the following element and options in index.rst:
Element: 
   ` .. toctree::`

Options:
 ```
   :maxdepth: 2
   :caption: Contents:
```
Include a comment that states the elements and options are applied to the following documents"
Documents:
  ```
   get-started
   spatial-raster
   spatial-vector
```

**Comment by jlpalomino** [comment]
@mcosmos12 Thanks for your issue. As the assignment is to identify two distinct changes that need to be made, please edit this issue title and comment to include one more proposed change. To count as a distinct change, the second proposed change will need to be something other than a spelling correction. Feel free to let us know if you have any questions.

**Comment by mcosmos12** [comment]
@jpalomino Yes no problem. This was done in class yesterday just to participate and follow along. I saw the directions for the assignment yesterday after class. I hope there are more interesting issues to fix! :)

**Comment by jlpalomino** [comment]
@mcosmos12 Your issue has been approved. Once you have made your changes, please submit a pull request (PR) with a tag to this issue (and @ to jlpalomino).

**Comment by lwasser** [comment]
closing this as the PR was just merged!
