### ISSUE TITLE
Correct the Code_of_Conduct link in CONTRIBUTING.rst

### ISSUE THREAD

**Issue by dcslagel** [earthlab/earthpy#628]
**Describe the bug**
In CONTRIBUTING.rst, the link to the EarthPy Code of Conduct currently displays `404 file not found`.
Also https://earthpy.readthedocs.io/en/latest/contributing.html's link to the Code of Conduct resolves to 404.

The current link in CONTRIBUTING.rst resolves to `https://github.com/earthlab/earthpy/blob/master/code-of-conduct.rst`

It should resolve to: `https://github.com/earthlab/earthpy/blob/master/CODE_OF_CONDUCT.rst` on GitHub.
Also it should resolve to: `https://earthpy.readthedocs.io/en/latest/code-of-conduct.html`  on ReadTheDocs.

**To Reproduce**
1. Go to: `https://github.com/earthlab/earthpy/blob/master/CONTRIBUTING.rst`
2. Click on ' EarthPy Code of Conduct.`
4. See error: `404 File not found`

**Expected behavior**
After clicking on `EarthPy Code of Conduct.` display the EarthPy Code of Conduct at: `https://github.com/earthlab/earthpy/blob/master/CODE_OF_CONDUCT.rst`

**Screenshots**
n/a

**What Operating System Are you Running? **
 - Mac

**Additional context**
n/a

**Comment by lwasser** [comment]
great catch @dcslagel !! thank you for noticing this and submitting this issue!! that link is absolutely broken!
