### ISSUE TITLE
Rename master to main

### ISSUE THREAD

**Issue by lwasser** [earthlab/earthpy#629]
i've been doing this slowly on all of our repos. We should do it here when we work on earthpy again!

**Comment by lwasser** [comment]
Closing this as it's been done !! really strange emoji responses to my comment above @nickmaev @ernytech ??

**Comment by NickMaev** [comment]
@lwasser all those pathetic campaigns related to renaming such things is about your mental problems, not software development. That's so ridiculous :smile:
