### ISSUE TITLE
Add documentation for Draw Legend function via rst file / Fix misspelling in stack_raster_tifs function in spatial.py

### ISSUE THREAD

**Issue by hdumke** [earthlab/earthpy#63]
## Identify the Documentation Element That You Propose to Update
1. Documentation for the draw-legend function is missing.
2. The word output is misspelled in the stack_raster_tifs function in spatial.py
## Please Identify Your Proposed Changes Below
1. Add documentation for the draw-legend function via an rst file.
2. Fix the misspelling of the word ouput to output.

**Comment by lwasser** [comment]
hi @hdumke do you plan to add docstring updates? I am not sure we need comments within the code for that function but updating the docstring would be useful. Or adding documentation via an rst file would also be useful. 

Your second change sounds excellent but please clarify the first change further before moving forward.

**Comment by lwasser** [comment]
ok @hdumke  looking at this is see it  says rst file!  Please go ahead and submit a pull request and flag this issue and me using @lwasser when you do so so i can review it!

**Comment by lwasser** [comment]
Closing this given the PR has been merged. Thank you again @hdumke !!
