### ISSUE TITLE
please delete the appeveyor project for earthpy

### ISSUE THREAD

**Issue by lwasser** [earthlab/earthpy#634]
https://ci.appveyor.com/project/mbjoseph/earthpy-d28d2
hi there @mbjoseph will you please delete the appveyor project for earthpy at the link  above? go to settings and chose "delete project"!! 

no more appveyor every again :) thank you so much. it's causing every commit to fail now! it hopefully is quick!!

**Comment by mbjoseph** [comment]
Done!

**Comment by lwasser** [comment]
thank you so very much @mbjoseph !!! :)that was speedy!
