### ISSUE TITLE
Windows 10 64-bit running python 3.8.5 cannot install earthpy, geopandas and rasterio

### ISSUE THREAD

**Issue by JLanghoff** [earthlab/earthpy#636]
Dear all

Having trouble installing: Running Windows 10, 64-bit with python 3.8.5 cannot install earthpy, geopandas and rasterio from the neither conda nor conda-forge channels. Have tried running the Anaconda Prompt with and without administrator - same frozen solve result.

Hope you can help.

Best from Denmark
Jesper

Jesper Heidemann Langhoff   
Adjunkt   Ph.d., cand.scient. & fotojournalist pba.
University College Copenhagen 
Institute for Læreruddannelse

**Comment by JLanghoff** [comment]
Same problem with macbook version 10.12.6 running python 3.8.1.

**Comment by JLanghoff** [comment]
Solution: on windows 10 I used miniconda3 in administrator anaconda prompt using conda-forge channel. Apparently the conflict is in anacondas many default libraries.

Please comment if other explanations make more sence. I'm still new in python (one month).

Best from Denmark
Jesper

**Comment by lwasser** [comment]
hi  @JLanghoff  !! my apologies for being so slow to respond. i suspected it was an envt issue. Essentially mixing  channels can be dangerous. we always suggest using miniconda (base install) and then  conda forge for  ALL  things that you install to avoid those issues. Your approach  above sounds  spot on! i will close this BUT if you  still have i ssues feel free to reopen. What i was going to look at  was your envt  -- outputs of 

`conda info` and 
`conda list`

conda list would tell me if you're mixing channels already in your install!!

**Comment by JLanghoff** [comment]
Hey Leah

It is all good :-) My new installation uses only the conda-forge channel.

Thanks much for your help.

Bedste hilsner
Jesper

[image: Adobe Systems]

*Jesper Heidemann Langhoff*

Adjunkt i geografi
Ph.d., cand.scient. & fotojournalist pba.

Læreruddannelsen

Institut for Læreruddannelse

Det Lærerfaglige Fakultet
+45 4189 75 82

jhof@kp.dk

Københavns Professionshøjskole
Humletorvet 3
1799 København


www.kp.dk <https://mail.google.com/mail/u/0/www.kp.dk>
