### ISSUE TITLE
main page of docs has a broken link to github

### ISSUE THREAD

**Issue by samsammurphy** [earthlab/earthpy#654]
**Describe the bug**
Incorrect URL link for 'Edit on Github' button on main page of docs

**To Reproduce**
1. Go to https://earthpy.readthedocs.io/en/latest/
2. Click on ..

![broken_link](https://user-images.githubusercontent.com/16657983/105014491-6854fa00-5a38-11eb-9301-ffc7ecbc6431.png)

**Expected behavior**
redirect to github

**Screenshots**
![github_404](https://user-images.githubusercontent.com/16657983/105014603-891d4f80-5a38-11eb-87cf-8976cc3f2f4c.png)

**Comment by lwasser** [comment]
@samsammurphy thank you for this  issue. i *think*  i know what is happening (we  renamed the master branch --> main)
i'm looking into it now!

**Comment by lwasser** [comment]
i believe that it's fixed now!! thank you so much @samsammurphy for noticing this. i will close the issue but if you still think  it is unresolved please reopen it!
