### ISSUE TITLE
Add unit tests to Crop_image function

### ISSUE THREAD

**Issue by lwasser** [earthlab/earthpy#70]
- [ ] Ensure that crop_image fun is provided with inputs in the right format (assert in the function
- [x] Ensure that the crop_image function raises an error if the incorrect formats are provided
@mbjoseph assigning this to you given today's meeting!

**Comment by mbjoseph** [comment]
Tests for crop_image need raster and polygon objects. Currently there is a pending PR to integrate raster data generation for testing that these tests would depend on: https://github.com/earthlab/earthpy/pull/45

**Comment by mbjoseph** [comment]
TODO: consider the edge case of cropping using an extent that is just a point (with zero area), e.g., something like the result of

```python
earthpy.spatial.extent_to_json([0, 0, 0, 0]) # [xmin, ymin, xmax, ymax]
```

For completeness, there is also the edge case of when the extent is a line, e.g.,

```python
earthpy.spatial.extent_to_json([0, 0, 1, 0])
```
