### ISSUE TITLE
Add .rst documentation for hillshade function in spatial.py AND add .rst documentation for crop_image function in spatial.py

### ISSUE THREAD

**Issue by andykeeton25** [earthlab/earthpy#72]
## Identify the Documentation Element That You Propose to Update
1. .rst file documentation for the hillshade function is missing.
2. .rst file documentation for the crop_image function is missing.

## Please Identify Your Proposed Changes Below
1. Add .rst file documentation for the hillshade function.
2. Add .rst file documentation for the crop_image function.

**Comment by lwasser** [comment]
hey @andykeeton25 please go ahead and submit the PR for this issue. Both items need to be updated!

**Comment by lwasser** [comment]
@andykeeton25 also 2 items
1. please ping me using @lwasser when you submit your PR and
2. please be sure to update your fork before submitting your PR!

**Comment by lwasser** [comment]
closing this issue as this has been complete. Great work @andykeeton25
