### ISSUE TITLE
Update spatial.py to conform to PEP-8 standards and update returns in spatial.py docstrings

### ISSUE THREAD

**Issue by mikedorfman** [earthlab/earthpy#74]
## Identify the Documentation Element That You Propose to Update
1.  Update spatial.py to conform to PEP-8 standards.
2.  Update several docstrings in spatial.py to include/update returned variables.

### Proposed change 1
a. Remove spaces around keyword assignments and adding spaces after commas on the following lines: 138, 170, 174, 175, 250, 282, 332, 338, 339, 340, 341, 342, 343, 344, 393, 394, 401, 402, 403, 404.
b.  Fix indentation on the following lines: 131, 132, 133, 134, 135, 301, 321, 322, 393, 425, 444. 
c.  Break up lines that are greater than 120 characters (in a couple of locations).
d.  Remove an unused import `from rasterio.mask import mask`

### Proposed change 2
a.  Function docstrings that need a description of the return added: `normalized_diff()`, `stack_raster_tifs()`.  
b.  Function docstrings that need their return description updated: `plot_bands()` (Function doesn't actually return anything.  Should this return the plt and/or ax object?), `plot_rgb()` (Function doesn't actually return anything.  Should this return the ax object as described?), `hist()` (Function doesn't actually return anything.  Should this return the plt and/or ax object?)

**Comment by lwasser** [comment]
hey @mikedorfman Thank you for this issue! This is quite a list of changes! If you'd like to work on all of this you are welcome to but just a heads up that you don't have to do that much for your homework!

Just a heads up that the plot functions should return figure / axis objects! Please be sure to update your fork BEFORE submitting these changes to ensure you have the most recent changes and also ping be using @lwasser when you submit your PR.

**Comment by mikedorfman** [comment]
@lwasser Thanks for the note - most of the clean-up was very similar, so it's easier to do it all at once.  Happy to contribute!
