### ISSUE TITLE
Add vignette to normalized_diff (spatial.py) AND add vignette to plot_bands (spatial.py) 

### ISSUE THREAD

**Issue by jeje1140** [earthlab/earthpy#83]
## Identify the Documentation Element That You Propose to Update
1. Add vignette to normalized_diff function in spatial.py

2. Add vignette to plot_bands function in spatial.py

## Please Identify Your Proposed Changes Below

1. Add 

`import numpy as np`

  ` import earthpy.spatial as es`

   ` red_band = np.array([[1, 2, 3, 4, 5],[11,12,13,14,15]])
    nir_band = np.array([[6, 7, 8, 9, 10],[16,17,18,19,20]])
    # Calculate normalized difference
    ndiff = es.normalized_diff(b2=nir_band, b1=red_band)`

2. Add 

` import earthpy.spatial as es`

   ` titles = ["Red Band", "Green Band", "Blue Band", "Near Infrared (NIR) Band"]`

   ` # Plot all bands of a raster tif
    es.plot_bands(naip_image,
                  title=titles,
                  figsize=(12,5),
                  cols=2)`

**Comment by lwasser** [comment]
hi @jeje1140  Thank you for this issue! 
Please have a close look at the issues that are listed (open ones in particular).

[This pull request](https://github.com/earthlab/earthpy/pull/81/files)
and[ this issue](https://github.com/earthlab/earthpy/issues/55) address what i believe you want to remove. The init file has also been cleaned out. [see here. ](https://github.com/earthlab/earthpy/blob/master/earthpy/__init__.py) there is a comment but it relates to data referenced in the file. I am trying to merge Pull requests now but why don't you update your fork and then try to find other items that have not yet been done. Please ping me when you have updated this issue!

**Comment by jeje1140** [comment]
@lwasser I believe I have found a new issue for the first one.  For the second.. does this require any docstring?

`def __init__(self, path=None):
        if path is None:
            path = op.join(HOME, DATA_NAME)
        self.path = path
        self.data_keys = list(DATA_URLS.keys())`

**Comment by lwasser** [comment]
hey @jeje1140  that def __init__ does not require a docstring in this case. I am also a bit confused as to what your first PR suggestion is.

Here is a suggestion if you are interested. It is nice to have vignettes in docstrings.

[look here](https://github.com/mapbox/rasterio/blob/master/rasterio/__init__.py#L143) to see that rasterio places vignettes in their docstrings! you could add a vignette to docstrings in earthpy. if you select 2 functions you might even find they have rst files with vignettes that you could add to the docstring like rasterio has! 

in the spatial.py file you will see the bytescale function has a docstring with a vignette. it's also probably the only function in all of earthpy to have a vignette in the docstring so you have a lot of options!

Please consider resubmitting this issue to me tonight so you can get this done by tomorrow before class.

**Comment by jeje1140** [comment]
@lwasser I have updated my issue

**Comment by lwasser** [comment]
looks good @jeje1140  please go ahead and submit a pr. When you do, please tag me using @lwasser so i see it was submitted and can review it. Also be sure to UPDATE your fork prior to beginning your edits. Finally please be sure to format the vignette following what i provided as an example with rasterio (or using bytescale in earthpy). Thank you!

**Comment by lwasser** [comment]
oh finally don't forget to reference this issue when you submit your pr!

**Comment by lwasser** [comment]
Closing this as it was implemented!! thank you again @jeje1140 !!
