### ISSUE TITLE
Several tests are failing

### ISSUE THREAD

**Issue by musicinmybrain** [earthlab/earthpy#844]
**Describe the bug**

Several tests are failing on `main`; we see the same failures when building the [`python-earthpy` package](https://src.fedoraproject.org/rpms/python-earthpy) with 0.9.4 on Fedora Linux 36, 37, and 38/Rawhide, except for `test_url_download_with_quotes` which is skipped because the build is offline.

**To Reproduce**
1. `$ gh repo clone earthlab/earthpy`
2. `$ cd earthpy`
3. `$ . _e/bin/activate`
4. `(_e) $ pip install -e .`
5. `(_e) $ pip install pytest`
6. `(_e) $ python -m pytest`

**Expected behavior**

All tests pass.

**Screenshots**

```
============================================== short test summary info ===============================================
FAILED earthpy/tests/test_crop_image.py::test_crop_image_with_one_point_raises_error - AssertionError: Regex pattern did not match.
FAILED earthpy/tests/test_crop_image.py::test_crop_image_with_1d_extent_raises_error - AssertionError: Regex pattern did not match.
FAILED earthpy/tests/test_hist.py::test_hist_number_of_columns - AttributeError: 'AxesSubplot' object has no attribute 'numCols'
FAILED earthpy/tests/test_io.py::test_url_download_with_quotes - AssertionError: assert (False)
ERROR earthpy/tests/test_clip.py::test_warning_mutli_point_clip_function - ValueError: Assigning CRS to a GeoDataFrame without a geometry column is not supported. Supply geometry using the...
================================ 4 failed, 161 passed, 20 warnings, 1 error in 27.01s ================================
```

**What Operating System Are you Running? **

Fedora Linux 37 x86_64

**Additional context**

I can reproduce this with at least Python 3.11, 3.10, and 3.9.

**Comment by musicinmybrain** [comment]
[Full pytest output](https://github.com/earthlab/earthpy/files/10608799/pytest.log)

**Comment by musicinmybrain** [comment]
While reporting this issue, I noticed that there is a typo in the name of the failing test `test_warning_mutli_point_clip_function`, which should be `test_warning_multi_point_clip_function`. Normally I would open a quick PR to fix the typo, but after seeing the PR template, I think I’ll just point it out here and let a maintainer fix it if they want to.

**Comment by nkorinek** [comment]
Thanks for the helpful issue, apologies for the long reply time here. Looking into this now and will update this issue when I've found the solution!

**Comment by nkorinek** [comment]
https://github.com/earthlab/earthpy/pull/878 This should be fixed with this PR!

**Comment by nkorinek** [comment]
New release within a month is planned! Going to add in one other small thing then push a release :)

**Comment by musicinmybrain** [comment]
> New release within a month is planned! Going to add in one other small thing then push a release :)

Awesome, thanks!
