### ISSUE TITLE
Add RST documentation to spatial-raster.rst for the functions plot_rgb() and hist() located in spatial.py

### ISSUE THREAD

**Issue by cstuart7** [earthlab/earthpy#85]
## Identify the Documentation Element That You Propose to Update
1. Add RST documentation to spatial-raster.rst for the function plot_rgb()
2. Add RST documentation to spatial-raster.rst for the function hist()

## Please Identify Your Proposed Changes Below
1. 
Plot RGB 
~~~~~~~~

The ``plot_rgb`` function plots each layer in a raster stack converted into a numpy array for quick visualization.

``plot_rgb`` takes 8 input parameters:

``arr``: numpy array
           An n-dimension numpy array in rasterio band order (bands, x, y)
``rgb``: list
           Indices of the three bands to be plotted (default = 0,1,2)
``extent``: tuple - optional
          The extent object that matplotlib expects (left, right, bottom, top)
``title``:  string- optional 
          String representing the title of the plot
``ax``: matplotlib AxesSubplot 
          The ax object where the ax element should be plotted. Default = none
``figsize``: tuple
          The x and y integer dimensions of the output plot if preferred to set.
``stretch``: boolean
          If True, a linear stretch will be applied
``str_clip``: int
         The % of clip to apply to the stretch. Default = 2 (2 and 98)

The ``plot_rgb`` function returns the following:

``fig, ax``: figure object, axes object
         The figure and axes object associated with the 3 band image.  If the ax keyword is specified, the figure return will be None.

Example:

.. code-block:: python

    import matplotlib as plt
    import earthpy.spatial as es

    fig, ax1 = plt.subplots(figsize=(12, 6))
    es.plot_rgb(naip_image,
                       rgb=[0, 1, 2],
                       extent=naip_extent,
                       title="NAIP 2017 Post Fire RGB Image",
                       ax=ax1)

2. 
Histogram 
~~~~~~~~~

The ``hist()`` function plots a histogram of each layer in a raster stack converted into a numpy array for quick visualization.

``hist()`` takes 6 input parameters:

``arr``: numpy array
         An dimension numpy array
``title``: list
         A list of title values that should either equal the number of bands or be empty, default = none
``colors``: list
         A list of color values that should either equal the number of bands or be a single color, (purple = default)
``cols``: int 
         The number of columns you want to plot in
``bins``: int
          The number of bins to calculate for the histogram
``figsize``: tuple
          The figsize if you'd like to define it. default: (12, 12)
    
The ``hist()`` function returns the following:

``fig, ax or axs`` : figure object, axes object
        The figure and axes object(s) associated with the histogram.

Example:

.. code-block:: python

    import earthpy.spatial as es

    colors = ['r', 'k', 'b', 'g', 'k', 'y', 'y']
    titles = ["Red Band", "Near Infrared (NIR) Band", "Blue/Green Band",
                 "Green Band", "Near Infrared (NIR) Band",
                 "Mid-infrared Band", "Mid-infrared Band"]

    # Plot histogram
    es.hist(modis_bands_pre_data,
                colors=colors,
                title=titles,
                cols=2)

**Comment by lwasser** [comment]
Hi @cstuart7 these items have been covered [in this issue](https://github.com/earthlab/earthpy/issues/55) and this [pull request](https://github.com/earthlab/earthpy/pull/81)

Please pay close attention to existing PR's and issues and update this issue accordingly with 2 unique changes.

**Comment by cstuart7** [comment]
@lwasser Corrected one of my changes to not duplicate the other issue that you identified.

**Comment by lwasser** [comment]
Hi Carmela,

Please read the assignment closely – posted in canvas. Then find 2 changes that each fit into the guidelines below. There is no vector module in the earthpy package so this proposed change is not correct but also does not follow the guidelines below.  There is however a file reserved for documenting functions related to vector data which is the file you mention but you need to work on documentation for a function in that file!

```

  *   Add documentation for one earthpy function to an .rst file in the docs dir (Links to an external site.)Links to an external site.<https://github.com/earthlab/earthpy/tree/master/docs>. This file will in turn add to the earthpy documentation (Links to an external site.)Links to an external site.<https://earthpy.readthedocs.io/en/latest/>. For example, add documentation for crop_image().
  *   Update module code (a single .py file) to meet PEP 8 guidelines.
  *   Update function docstring documentation given typos, or missing function arguments.
     *   Following rasterio documentation, each function argument should be documented using the prescribed  docstring syntax
  *   Update / Cleanup and remove commented out code and extraneous comments from a function.

```

**Comment by cstuart7** [comment]
@lwasser Ok, re-did my issue to be better suited to requirements in Canvas.

**Comment by lwasser** [comment]
Thank you @cstuart7 . This is a good start. 

One point to consider when you submit your pr:

`The ``plot_rgb`` function plots each layer in a raster stack converted into a numpy array for quick visualization.`

The plot_rgb function actually takes a 3 dimensional numpy array that contains image data and plots the 3 bands together to create a composite image. When you submit your PR - please review the lessons to recall what the functions do. The documentation should be very user friendly !

Please go ahead and work on your PR. When you are happy with it, ping me using @lwasser and reference this issue as well via a link. Thank you!

**Comment by lwasser** [comment]
closing this as the PR was merged. Thank you again @cstuart7
