### ISSUE TITLE
Update environment.yml to reflect dependencies not the ea envt in it's total form

### ISSUE THREAD

**Issue by lwasser** [earthlab/earthpy#97]
Hey @mbjoseph  just curious at this point with our testing setup if we want a yaml file
This one: is not representative of our dependencies. there are many more things there that we don't need. it's also an old version of the ea-environment. i'd like to understand what this file should contain IF we need it! 

https://github.com/earthlab/earthpy/blob/master/environment.yml

**Comment by mbjoseph** [comment]
Hey @lwasser - yes until we move away from conda, the build on Travis still expects to find an `environment.yml` file. The relevant lines are here: https://github.com/earthlab/earthpy/blob/master/.travis.yml#L19-L20

If you wanted to trim down the dependencies in that file to be limited to the dependencies of the earthpy package, that would probably be good. It should make our builds faster on Travis. While we are at it, we should also not use `earth-analytics-python` as the name for the environment associated with earthpy, to avoid confusion with your earth analytics python environment that is in a separate repo.

**Comment by lwasser** [comment]
eeks -- well i messed up and didn't see i was on  master but this has been atleast cleaned up [here](https://github.com/earthlab/earthpy/commit/506748bd867c913cf4b210b2855e0814909856ef)

**Comment by lwasser** [comment]
i think we can get rid of all of this:
can you think of any reason we migth want it @mbjoseph  ?

```
  # Jupyter Environment
  - notebook
  - ipython
  - jupyter_contrib_nbextensions
  - nb_conda
  - jupyterlab
```

**Comment by lwasser** [comment]
yml file has been updated [here](91d88bccb2e2dc39342e6b2eaa2c3b504d6ad23b) renamed the envt, removed items that don't relate to this package and updated travis build accordingly. Closing this for the time being but we can reopen if need be.
